(()=>{const D=window.DATA,$=s=>document.querySelector(s),V=$("#view");
const store={get(){try{return JSON.parse(localStorage.getItem("mhTrainer")||"{}")}catch(e){return{}}},set(o){try{localStorage.setItem("mhTrainer",JSON.stringify(o))}catch(e){}}};
let S=Object.assign({quiz:{},known:[],cases:{}},store.get());const save=()=>store.set(S);
const esc=t=>String(t).replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));
const shuffle=a=>{a=a.slice();for(let i=a.length-1;i>0;i--){const j=Math.random()*(i+1)|0;[a[i],a[j]]=[a[j],a[i]]}return a};
const tabs={home,law,sdoh,disclose,sec13,forms,viol,audit,rights,ex,lib,comm,quiz,cards,cases,capacity,review,screen,ref,glossary};
const navGroups=[
  ["LEARN",[["home","Home","⌂"],["law","The Act","▤"],["glossary","Glossary","Aa"],["sdoh","Determinants","◉"],["disclose","Confidentiality","◌"],["sec13","Sec. 13","▣"],["forms","Forms","▤"],["viol","Violations","⚑"],["audit","Facility audit","▧"],["rights","Rights & complaints","♡"]]],
  ["APPLY",[["ex","Exercises","◇"],["lib","Interventions","✳"],["comm","Community","♧"]]],
  ["PRACTICE",[["quiz","Quiz","▣"],["cards","Flashcards","▤"],["cases","Cases","♧"],["capacity","Capacity","◉"]]],
  ["TOOLS",[["review","15-day IRB","▦"],["screen","Social screen","⊙"],["ref","Act reference map","☷"]]]
];
const names=Object.fromEntries(navGroups.flatMap(g=>g[1].map(x=>[x[0],x[1]])));
$("#nav").innerHTML=navGroups.map(([group,items])=>`<section class="nav-group"><div class="nav-group-label">${group}</div>${items.map(([k,label,icon])=>`<button data-k="${k}" aria-label="${label}"><span class="nav-icon" aria-hidden="true">${icon}</span><span>${label}</span></button>`).join("")}</section>`).join("");
$("#nav").onclick=e=>{const b=e.target.closest("button[data-k]");if(b)go(b.dataset.k)};
function go(k){document.querySelectorAll("#nav button").forEach(b=>{const active=b.dataset.k===k;b.classList.toggle("on",active);if(active)b.setAttribute("aria-current","page");else b.removeAttribute("aria-current")});V.oninput=null;tabs[k]();window.scrollTo(0,0);location.hash=k;document.body.classList.remove("nav-open");$("#menu-toggle").setAttribute("aria-expanded","false")}
const root=document.documentElement,themeButton=$("#theme-toggle"),themeLabel=themeButton.querySelector(".theme-label"),themeIcon=themeButton.querySelector(".theme-icon"),themeSwitch=themeButton.querySelector(".theme-switch");
function setTheme(theme){root.dataset.theme=theme;const dark=theme==="dark";themeLabel.textContent=dark?"Dark mode":"Light mode";themeIcon.textContent=dark?"☾":"☼";themeSwitch.classList.toggle("is-dark",dark);themeButton.setAttribute("aria-label",`Switch to ${dark?"light":"dark"} mode`);document.querySelector('meta[name="theme-color"]').content=dark?"#071815":"#f7f6f0";try{localStorage.setItem("mhTrainerTheme",theme)}catch(e){}}
let savedTheme="light";try{savedTheme=localStorage.getItem("mhTrainerTheme")||"light"}catch(e){}setTheme(savedTheme);
themeButton.onclick=()=>setTheme(root.dataset.theme==="dark"?"light":"dark");
$("#menu-toggle").onclick=()=>{const open=!document.body.classList.contains("nav-open");document.body.classList.toggle("nav-open",open);$("#menu-toggle").setAttribute("aria-expanded",String(open))};
$("#sidebar-backdrop").onclick=()=>{document.body.classList.remove("nav-open");$("#menu-toggle").setAttribute("aria-expanded","false")};

function home(){const q=Object.values(S.quiz),ans=q.length,ok=q.filter(x=>x).length,cs=Object.keys(S.cases).length;
V.innerHTML=`<h2>Rights-based care meets social action</h2><p class="mut">A trainer for psychiatry residents on RA 11036 (Mental Health Act of 2018) and the social determinants of mental health (WHO &amp; Gulbenkian, 2014), set in everyday Philippine practice.</p>
<div class="grid"><div class="card"><div class="stat">${ok}/${D.quiz.length}</div>quiz questions mastered</div><div class="card"><div class="stat">${S.known.length}/${D.cards.length}</div>flashcards known</div><div class="card"><div class="stat">${cs}/${D.cases.length}</div>cases completed</div></div>
<div class="card"><h3>Where to start</h3><p>Run a <b>case</b> to see the law and the social context together, drill with the <b>quiz</b>, then use the <b>capacity</b>, <b>15-day IRB</b> and <b>social screen</b> tools as bedside templates.</p><button class="btn" onclick="document.querySelector('[data-k=cases]').click()">Start a case</button> <button class="btn alt" id="rs">Reset progress</button></div>
<p class="note">Educational use only. Not legal advice. Check the current IRR and your institution's policies. Cases are fictional.</p>`;
$("#rs").onclick=()=>{if(confirm("Reset all saved progress?")){S={quiz:{},known:[],cases:{}};save();home()}}}

function quiz(){let topics=["All",...new Set(D.quiz.map(x=>x.t))];
V.innerHTML=`<h2>Quiz</h2><p>Topic: <select id="tp">${topics.map(t=>`<option>${t}</option>`).join("")}</select> <button class="btn" id="go">Start</button></p><div id="qa"></div>`;
$("#go").onclick=()=>{const t=$("#tp").value,L=shuffle(D.quiz.map((x,i)=>({...x,i})).filter(x=>t==="All"||x.t===t));let n=0,sc=0;
const show=()=>{if(n>=L.length){$("#qa").innerHTML=`<div class="card"><h3>Score: ${sc}/${L.length}</h3><button class="btn" id="again">Again</button></div>`;$("#again").onclick=()=>$("#go").click();return}
const x=L[n];$("#qa").innerHTML=`<div class="card"><div class="tag">${x.t} &middot; ${n+1}/${L.length}</div><div class="bar"><i style="width:${n/L.length*100}%"></i></div><h3 style="margin-top:12px">${esc(x.q)}</h3>${x.o.map((o,i)=>`<button class="opt" data-i="${i}">${esc(o)}</button>`).join("")}<div id="fb"></div></div>`;
document.querySelectorAll(".opt").forEach(b=>b.onclick=()=>{const i=+b.dataset.i,good=i===x.a;document.querySelectorAll(".opt").forEach(o=>{o.disabled=true;if(+o.dataset.i===x.a)o.classList.add("ok")});if(!good)b.classList.add("no");sc+=good;S.quiz[x.i]=good;save();
$("#fb").innerHTML=`<div class="fb">${esc(x.e)}</div><p><button class="btn" id="nx">${n+1<L.length?"Next":"Finish"}</button></p>`;$("#nx").onclick=()=>{n++;show()}})};show()}}

function cards(){let L=shuffle(D.cards.map((c,i)=>({c,i}))),n=0,flip=false;
const r=()=>{const x=L[n];V.innerHTML=`<h2>Flashcards</h2><div class="card fc" id="fc"><div>${flip?esc(x.c[1]):`<b>${esc(x.c[0])}</b><div class="note">tap to reveal</div>`}</div></div><p class="note">${n+1}/${L.length} &middot; ${S.known.length} known</p>
<button class="btn alt" id="pv">Back</button> <button class="btn alt" id="kn">${S.known.includes(x.i)?"Unmark known":"Mark known"}</button> <button class="btn" id="nx">Next</button>`;
$("#fc").onclick=()=>{flip=!flip;r()};$("#nx").onclick=()=>{n=(n+1)%L.length;flip=false;r()};$("#pv").onclick=()=>{n=(n-1+L.length)%L.length;flip=false;r()};
$("#kn").onclick=()=>{S.known=S.known.includes(x.i)?S.known.filter(k=>k!==x.i):[...S.known,x.i];save();r()}};r()}

function cases(){V.innerHTML=`<h2>Case simulator</h2>${D.cases.map((c,i)=>`<div class="card"><h3>${esc(c.title)} ${S.cases[i]!=null?`<span class="tag">done ${S.cases[i]}/${c.steps.length}</span>`:""}</h3><p class="mut">${esc(c.intro)}</p><button class="btn" data-c="${i}">Open case</button></div>`).join("")}`;
document.querySelectorAll("[data-c]").forEach(b=>b.onclick=()=>runCase(+b.dataset.c))}
function runCase(ci){const c=D.cases[ci];let n=0,good=0;
const step=()=>{if(n>=c.steps.length){S.cases[ci]=good;save();V.innerHTML=`<div class="card"><h3>${esc(c.title)}: first-try score ${good}/${c.steps.length}</h3><p>The legal answer is half the job. The social column is what prevents readmission.</p><button class="btn" id="bk">Back to cases</button></div>`;$("#bk").onclick=cases;return}
const s=c.steps[n],need=s.o.filter(o=>o[1]).length;let hit=0,first=true;
V.innerHTML=`<div class="card"><div class="tag">${esc(c.title)} &middot; step ${n+1}/${c.steps.length}</div><p class="mut">${esc(c.intro)}</p><h3>${esc(s.q)}${s.multi?" <span class='note'>(select all that apply)</span>":""}</h3>${s.o.map((o,i)=>`<button class="opt" data-i="${i}">${esc(o[0])}</button>`).join("")}<div id="fb"></div></div>`;
document.querySelectorAll(".opt").forEach(b=>b.onclick=()=>{const o=s.o[+b.dataset.i];if(b.disabled)return;b.disabled=true;b.classList.add(o[1]?"ok":"no");
if(first){first=false;if(!o[1])good-=0;else if(!s.multi)good++}
if(o[1])hit++;if(s.multi&&hit===need&&first===false&&!document.querySelector(".opt.no"))good++;
$("#fb").insertAdjacentHTML("beforeend",`<div class="fb">${esc(o[2])}</div>`);
if(hit>=need){$("#fb").insertAdjacentHTML("beforeend",`<p><button class="btn" id="nx">${n+1<c.steps.length?"Next step":"Finish"}</button></p>`);$("#nx").onclick=()=>{n++;step()}}})};step()}

function capacity(){const A=[["Understands information about the condition (Sec. 4g-1)","Can you tell me in your own words what is happening to you?"],["Understands consequences of decisions for self and others (4g-2)","What might happen if you take this medicine? If you don't?"],["Understands the proposed treatment: method, effects, side effects (4g-3)","What do you know about how it works and its side effects?"],["Can communicate consent or information about own condition (4g-4)","What have you decided? Offer interpreter or alternative communication."]];
V.innerHTML=`<h2>Capacity checker</h2><p class="mut">Decision-specific and time-limited. Tick what the person <b>can</b> do after supports are offered. Presumption of capacity applies (Sec. 8).</p><div class="card"><label>Decision being assessed: <input id="dc" placeholder="e.g. accept injectable medication" style="width:100%;padding:9px;margin:6px 0"></label>${A.map((a,i)=>`<label class="chk"><input type="checkbox" class="ab" data-i="${i}"><span><b>${a[0]}</b><br><span class="note">${a[1]}</span></span></label>`).join("")}<label class="chk"><input type="checkbox" id="sp"><span>Supports offered first (language, supporters per Sec. 11, communication aids)</span></label><div id="out"></div></div>`;
const upd=()=>{const n=[...document.querySelectorAll(".ab")].filter(x=>x.checked).length,imp=n<4;$("#out").innerHTML=`<div class="fb"><b>${imp?"Possible impairment or temporary loss of capacity for this decision":"Capacity present for this decision"}</b> (${n}/4 abilities).${imp?" If the person is unable on any of the four, document which, then reassess as they improve. Consent exceptions apply only under Sec. 13 safeguards.":" Respect the decision, record written consent (Sec. 8)."}${$("#sp").checked?"":"<br>Offer supports before concluding."}</div><p class="note">Chart note: Decision: ${esc($("#dc").value||"[ ]")}. Abilities met: ${n}/4. Supports offered: ${$("#sp").checked?"yes":"no"}. Reassess: [date].</p>`};
V.oninput=upd;upd()}

function review(){const f=d=>d.toLocaleDateString("en-PH",{weekday:"short",year:"numeric",month:"short",day:"numeric"});
V.innerHTML=`<h2>15-day IRB review tracker (Sec. 13c)</h2><div class="card"><p>Date the order was issued: <input type="date" id="od"></p><div id="rv"></div></div><p class="note">Reviews fall within 15 days of the order and every 15 days while treatment or restraint continues. Stop once the emergency or incapacity ends. Also check rights told within 24h (Sec. 5s).</p>`;
const o=$("#od");o.valueAsDate=new Date();const u=()=>{if(!o.value)return;const b=new Date(o.value+"T00:00:00");$("#rv").innerHTML=`<table><tr><th>Review</th><th>Due on or before</th></tr>${[15,30,45,60].map((d,i)=>`<tr><td>${i?"Repeat #"+i:"First review"}</td><td>${f(new Date(b.getTime()+d*864e5))}</td></tr>`).join("")}</table><p class="note">Rights explained by: ${new Date(b.getTime()+864e5).toLocaleDateString("en-PH")} (24h from admission).</p>`};o.oninput=u;u()}

function screen(){V.innerHTML=`<h2>Social risk screen</h2><p class="mut">Ask in every assessment (WHO multilevel framework). Tick positives to build a referral and coding list.</p><div class="card">${D.screen.map((s,i)=>`<label class="chk"><input type="checkbox" data-i="${i}"><span><b>${s.d}</b><br>${esc(s.ask)}</span></label>`).join("")}</div><div class="card"><h3>Plan</h3><div id="pl" class="mut">No risks ticked.</div></div><p class="note">Z-code families are ICD-10 style. Confirm exact codes in your coding system. Referral links are suggestions drawn from the Act.</p>`;
V.oninput=()=>{const p=[...document.querySelectorAll("[data-i]:checked")].map(x=>D.screen[+x.dataset.i]);$("#pl").innerHTML=p.length?`<table><tr><th>Domain</th><th>Document</th><th>Refer</th></tr>${p.map(s=>`<tr><td>${s.d}</td><td>${esc(s.z)}</td><td>${esc(s.r)}</td></tr>`).join("")}</table><p class="note">Name each action as reducing exposure or strengthening buffers.</p>`:"No risks ticked."}}

function ref(){V.innerHTML=`<h2>RA 11036 quick map</h2><div class="card"><table><tr><th>Sec.</th><th>Topic</th><th>Key points</th></tr>${D.ref.map(r=>`<tr><td>${r[0]}</td><td><b>${r[1]}</b></td><td>${esc(r[2])}</td></tr>`).join("")}</table></div><p class="note">Source text: <a href="https://elibrary.judiciary.gov.ph/thebookshelf/showdocs/2/83255" target="_blank" rel="noopener">RA 11036, Supreme Court E-Library</a>. WHO &amp; Calouste Gulbenkian Foundation (2014). <i>Social determinants of mental health.</i> Geneva: WHO. NCMH crisis line 1553 (verify numbers before distribution).</p>`}
function law(){const L=window.LAW;V.innerHTML=`<h2>RA 11036: the Mental Health Act</h2><p class="mut">Tap a chapter, then a section. Short sections are near-verbatim; long ones are condensed. <a href="https://elibrary.judiciary.gov.ph/thebookshelf/showdocs/2/83255" target="_blank" rel="noopener">Official text</a>.</p><input id="lq" placeholder="Search the Act (e.g. restraint, 15 days)" style="width:100%;padding:10px;border:1px solid var(--line);border-radius:8px;margin-bottom:8px;background:var(--card);color:var(--ink)"><div id="lw"></div>`;
const draw=q=>{q=q.toLowerCase();$("#lw").innerHTML=L.map(c=>{const ss=c.s.filter(x=>!q||(x[0]+x[1]+x[2]).toLowerCase().includes(q));const roman=(c.c.match(/Chapter\s+([IVX]+)/i)||[])[1]||"";return ss.length?`<div class="card" id="act-chapter-${roman}" data-act-chapter="${roman}"><div class="tag">${c.c}</div><h3>${c.t}</h3>${ss.map(x=>`<details id="act-sec-${x[0]}" data-act-section="${x[0]}" ${q?"open":""}><summary><b>Sec. ${x[0]}.</b> ${esc(x[1])}</summary><p>${esc(x[2]).replace(/\n/g,"<br>")}</p></details>`).join("")}</div>`:""}).join("")||"<p>No matches.</p>"};
$("#lq").oninput=e=>draw(e.target.value);draw("")}
function sdoh(){const L=window.SDOH;V.innerHTML=`<h2>Social determinants of mental health</h2><p class="mut">Source: WHO &amp; Calouste Gulbenkian Foundation (2014). Philippine links to RA 11036 shown for each. Every intervention either reduces exposure or strengthens buffers.</p>${L.map(x=>`<details class="card"><summary><b>${esc(x.n)}</b></summary><p>${esc(x.w)}</p><div class="tag">Evidence</div><p>${esc(x.e)}</p><div class="tag">In clinic</div><p>${esc(x.c)}</p><div class="tag">RA 11036</div><p>${esc(x.a)}</p></details>`).join("")}`}

const mode=(id,ms,cur,fn)=>`<p id="${id}">${ms.map(m=>`<button class="btn ${m[0]===cur?"":"alt"}" data-m="${m[0]}">${m[1]}</button>`).join(" ")}</p>`;
const wire=(id,fn)=>document.querySelectorAll("#"+id+" [data-m]").forEach(b=>b.onclick=()=>fn(b.dataset.m));

function disclose(m="tree"){
const Q=[["Consent","Has the service user (or the legal representative, if the user lacks capacity) consented to this disclosure?","Disclose only what the consent covers, to the person named. Sec. 5(l) calls for written consent; record it in the chart. A spouse is the default representative only when the patient is assessed as lacking capacity (Sec. 10)."],
["Law or court order","Is disclosure required by law, or by an order of a court of competent jurisdiction?","Verify the order itself. A lawyer's letter or a police request is not a court order. Involve hospital counsel, disclose the minimum required, and document (Sec. 5l-1)."],
["Life-threatening emergency","Is there a life-threatening emergency, and is disclosure necessary to prevent harm to the user or to others?","Disclose only what is needed, to the person who can prevent the harm (e.g., a threatened person, security, family at the bedside). Document what, to whom and why (Sec. 5l-3)."],
["Child abuse","Is the user a minor whom you reasonably believe to be a victim of child abuse?","Disclose through your institution's child-protection pathway (e.g., social services). Tell the child honestly what will be shared and why (Sec. 5l-4, Sec. 8). Check separate mandatory-reporting rules."],
["Case against a professional","Is disclosure needed in an administrative, civil or criminal case against a mental health professional or worker for negligence or ethics breach?","Disclose only to the extent necessary to resolve the issue, through counsel or the hearing body (Sec. 5l-5)."]];
const S=[["HR of an employee's company calls to ask whether he was admitted.",-1,"No exception applies. Do not even confirm admission."],["A patient with a plan to kill a named neighbor refuses to let you tell anyone.",2,"Life-threatening emergency: disclose what is necessary to prevent harm."],["A lawyer sends a subpoena-style letter, signed by no judge, asking for a chart.",-1,"Not a court order. Ask for a court order and involve hospital counsel."],["A 13-year-old discloses sexual abuse by an uncle and begs you to keep it secret.",3,"Suspected child abuse of a minor. Explain honestly what you must share."],["A patient with capacity signs a release letting you share her summary with her sister.",0,"Consent, kept in the chart and limited to what she approved."],["You are the respondent in a negligence complaint and use the chart in your defense.",4,"Allowed only to the extent necessary to resolve the case."],["A husband demands the diagnosis; his wife has capacity and says no.",-1,"The spouse acts as representative only when capacity is impaired (Sec. 10c)."]];
const opts=[...Q.map(q=>q[0]),"None apply"];
V.innerHTML=`<h2>Can I disclose?</h2><p class="mut">Sec. 5(l): confidentiality is the rule; there are five exceptions. Violation is punishable under Sec. 44(b).</p>`+mode("dm",[["tree","Decision tree"],["drill","Practice"]],m)+`<div id="dv"></div>`;wire("dm",disclose);
const D=$("#dv");
if(m==="tree"){let i=0;const r=()=>{if(i>=Q.length){D.innerHTML=`<div class="card"><h3>Do not disclose</h3><p>No exception applies. Instead: ask the patient for consent (written, specific); listen to family without confirming or denying details; share general, non-identifying information (e.g., how to cope, how to reach the service); document the request and your response.</p><button class="btn alt" id="rs2">Start over</button></div>`;$("#rs2").onclick=()=>{i=0;r()};return}
const q=Q[i];D.innerHTML=`<div class="card"><div class="tag">Step ${i+1}/${Q.length} &middot; ${q[0]}</div><h3>${q[1]}</h3><button class="btn" id="y">Yes</button> <button class="btn alt" id="n">No</button></div>`;
$("#y").onclick=()=>{D.innerHTML=`<div class="card"><h3 style="color:var(--ok)">Disclosure may be permitted: ${q[0]}</h3><p>${q[2]}</p><p class="note">Limit to the minimum necessary and document who, what, when and why.</p><button class="btn alt" id="rs2">Start over</button></div>`;$("#rs2").onclick=()=>{i=0;r()}};$("#n").onclick=()=>{i++;r()}};r()}
else{let n=0,sc=0;const r=()=>{if(n>=S.length){D.innerHTML=`<div class="card"><h3>Score ${sc}/${S.length}</h3><button class="btn" id="ag">Again</button></div>`;$("#ag").onclick=()=>disclose("drill");return}
const s=S[n];D.innerHTML=`<div class="card"><div class="tag">${n+1}/${S.length}</div><h3>${esc(s[0])}</h3>${opts.map((o,i)=>`<button class="opt" data-i="${i}">${o}</button>`).join("")}<div id="fb"></div></div>`;
document.querySelectorAll(".opt").forEach(b=>b.onclick=()=>{const i=+b.dataset.i,want=s[1]<0?opts.length-1:s[1];document.querySelectorAll(".opt").forEach(o=>{o.disabled=true;if(+o.dataset.i===want)o.classList.add("ok")});if(i!==want)b.classList.add("no");else sc++;$("#fb").innerHTML=`<div class="fb">${s[2]}</div><p><button class="btn" id="nx">Next</button></p>`;$("#nx").onclick=()=>{n++;r()}})};r()}}

function sec13(){const G=[["Trigger (Sec. 13 lead-in)",["A psychiatric or neurologic emergency exists, OR a mental health professional has assessed impaired or temporarily lost decision-making capacity (Sec. 4g)","Least restrictive options tried or considered first (Sec. 14c, 19a)","Rights explained within 24h of admission, in language understood (Sec. 5s)"]],
["(a) Advance directive",["Checked for a signed, dated, notarized advance directive and followed it","If deviating: documented the immediate risk of serious harm to the patient or another person"]],
["(b) Necessity and duration",["Intervention limited to what is necessary","End criteria written: reassess capacity/emergency and stop when it ends"]],
["(c) Order and IRB review",["Order issued by the attending mental health professional (name, date, time)","IRB review scheduled within 15 days, then every 15 days while it continues","Legal representative or supporters informed (Secs. 10-11)"]],
["(d) Guidelines and documentation",["Applied per approved facility guidelines with clear start and stop criteria","Fully documented in the chart and the treatment register (Sec. 19e)","Open to external independent monitoring, review and audit by the IRB"]]];
V.innerHTML=`<h2>Sec. 13 restraint and involuntary treatment checklist</h2><p class="mut">For physical or chemical restraint, treatment or confinement without consent. Observation frequency, drug choice and doses come from your facility guidelines and the IRR, not this app. Nothing here is saved.</p><div class="card"><p>Date of order: <input type="date" id="od2"> Type: <select id="ty"><option>physical restraint</option><option>chemical restraint</option><option>involuntary treatment</option><option>involuntary confinement</option></select></p>${G.map((g,gi)=>`<h3>${g[0]}</h3>${g[1].map((t,i)=>`<label class="chk"><input type="checkbox" data-g="${gi}" data-i="${i}"><span>${t}</span></label>`).join("")}`).join("")}</div><div class="card"><h3>IRB review dates</h3><div id="rv2"></div><h3>Chart note draft</h3><textarea id="nt" rows="9" style="width:100%;padding:9px;background:var(--card);color:var(--ink);border:1px solid var(--line);border-radius:8px"></textarea><p><button class="btn" id="cp">Copy note</button> <span id="ok" class="note"></span></p></div>`;
const o=$("#od2");o.valueAsDate=new Date();
const u=()=>{const b=o.value?new Date(o.value+"T00:00:00"):null,f=d=>d.toLocaleDateString("en-PH",{weekday:"short",year:"numeric",month:"short",day:"numeric"}),
done=[...document.querySelectorAll("[data-g]")].map(x=>[x.checked,x.parentElement.textContent.trim()]);
$("#rv2").innerHTML=b?`<table><tr><th>Review</th><th>Due on or before</th></tr>${[15,30,45].map((d,i)=>`<tr><td>${i?"Repeat #"+i:"First"}</td><td>${f(new Date(b.getTime()+d*864e5))}</td></tr>`).join("")}</table>`:"Enter the order date.";
$("#nt").value=`Sec. 13 (RA 11036) ${$("#ty").value}. Order date: ${o.value||"[ ]"}.\n`+done.map(d=>(d[0]?"[x] ":"[ ] ")+d[1]).join("\n")+`\nIRB review due: ${b?f(new Date(b.getTime()+15*864e5)):"[ ]"} then every 15 days. Reassess: [date/time]. Attending MHP: [name].`;};
V.oninput=u;u();$("#cp").onclick=()=>{navigator.clipboard.writeText($("#nt").value).then(()=>$("#ok").textContent="Copied",()=>{$("#nt").select();$("#ok").textContent="Select and copy manually"})}}

function ex(m="life"){
const ST=[["Prenatal","Poor maternal nutrition; smoking, alcohol or drug misuse; stress; heavy physical labor; maternal depression (about 16% antenatal in LMICs); intimate partner violence.","Partner support, maternal education, stable job.","Screen and treat maternal depression; trained community health workers; antenatal support.","Secs. 15, 27"],
["Early years","Neglect, abuse, domestic violence, insecure attachment; debt and poverty stress; maternal mental illness (children 5x more likely to have a disorder).","A loving, stable caregiver; secure attachment; wider family and community.","Home visiting; parenting programs (Triple P, Incredible Years); early childhood education; Sure Start-type services.","Secs. 6, 8, 5(l)(4)"],
["Later childhood and adolescence","Overcrowded, unhealthy homes; adverse childhood experiences; substance use. Depressed mood or anxiety 2.5x higher in low-SES youth aged 10-15.","School connectedness, peers, social and emotional skills.","Universal whole-school programs; teacher training; parent liaison; accurate information on substances.","Secs. 21, 23, 24, 34"],
["Working age and family building","Unemployment, insecure or low-control work, debt, alcohol; postnatal depression (England: over 20% lowest vs 7% highest quintile).","Job security and control, adequate income, partner support.","Active labour market programs; workplace programs; minimum wage; flexible microfinance; maternal services.","Secs. 25, 35, 36, 37(f)"],
["Older ages","Bereavement, living alone, isolation, poor physical health, loss of status.","Social contact, volunteering, education, faith or community groups.","Befriending; social and creative programs; exercise; heating improvements; BHW home visits.","Secs. 5(i), 16, 27, 37(h)"]];
const LV=["Life course","Family and household","Community","Local services","Country level"];
const CH=[["Mario's father drank heavily and the family was poor when he was a child.",0,"Adversity in early life accumulates across the life course."],["Mario lost his jeepney route three months ago.",1,"Employment and income sit at the household level in the WHO framework."],["He owes an informal lender and fears collection.",1,"Debt raises risk even after adjusting for income."],["His mother has long-standing depression.",1,"Parental mental health is a household factor."],["His barangay has no psychiatric service; the nearest ward is hours away.",3,"Access to local health services."],["Floods repeatedly damage homes in his neighborhood, and neighbors distrust each other.",2,"Community: trust, safety and the natural and built environment."],["The country lacks unemployment protection for informal workers.",4,"Social protection and national policy are country-level factors."],["The barangay school offers no mental health program.",3,"Local services include schools and youth services."]];
V.innerHTML=`<h2>Life-course and multilevel exercises</h2>`+mode("em",[["life","Life-course timeline"],["multi","Multilevel sorting"],["prop","Proportionate universalism"]],m)+`<div id="ev"></div>`;wire("em",ex);const E=$("#ev");
if(m==="life"){const sh=i=>{const s=ST[i];E.innerHTML=`<div class="card"><p>${ST.map((t,j)=>`<button class="btn ${j===i?"":"alt"}" data-s="${j}" style="margin:2px">${t[0]}</button>`).join("")}</p><h3>${s[0]}</h3><div class="tag">Risks</div><p>${s[1]}</p><div class="tag">Buffers</div><p>${s[2]}</p><div class="tag">Actions</div><p>${s[3]}</p><div class="tag">RA 11036</div><p>${s[4]}</p></div><div class="card"><div class="tag">Across all stages</div><p>Disadvantage starts before birth and accumulates; inequity is passed between generations. Actions should be universal yet proportionate to need (proportionate universalism), with the strongest evidence for giving every child the best start.</p><p class="note">Source: WHO &amp; Calouste Gulbenkian Foundation (2014), pp. 16-35, 39-40.</p></div>`;document.querySelectorAll("[data-s]").forEach(b=>b.onclick=()=>sh(+b.dataset.s))};sh(0)}
else if(m==="multi"){E.innerHTML=`<p class="mut">Mario, 32 (from the ER case): place each stressor at the level of the WHO multilevel framework where it mainly operates.</p><div class="card">${CH.map((c,i)=>`<div style="margin:10px 0"><div>${esc(c[0])}</div><select data-i="${i}"><option value="">Choose level</option>${LV.map((l,j)=>`<option value="${j}">${l}</option>`).join("")}</select><div class="note" id="x${i}"></div></div>`).join("")}<button class="btn" id="ck">Check</button> <span id="sc"></span></div><p class="note">Several stressors could act at more than one level; the point is to widen your view beyond the individual.</p>`;
$("#ck").onclick=()=>{let s=0;CH.forEach((c,i)=>{const sel=document.querySelector(`select[data-i="${i}"]`),ok=sel.value!==""&&+sel.value===c[1];s+=ok;sel.style.borderColor=ok?"var(--ok)":"var(--bad)";$("#x"+i).textContent=(ok?"Correct. ":"Best fit: "+LV[c[1]]+". ")+c[2]});$("#sc").textContent=s+"/"+CH.length}} else propEx(E)}


function propEx(E){
const P=[["Highest income",13.5],["2nd",10.75],["Middle",15],["4th",20],["Lowest income",24.25]],T=P.reduce((s,p)=>s+p[1],0),K=25;
const PRE={targeted:[0,0,0,0,100],equal:[20,20,20,20,20],prop:P.map(p=>+(p[1]/T*100).toFixed(1))};
let A=PRE.equal.slice();
E.innerHTML=`<p class="mut">You have 100 units of mental health investment for five income groups of equal size. WHO's principle: universal, but scaled to need. Try the three presets, then adjust the sliders.</p><p><button class="btn alt" data-p="targeted">Targeted: lowest group only</button> <button class="btn alt" data-p="equal">Universal: equal shares</button> <button class="btn alt" data-p="prop">Proportionate universal</button></p><div class="card">${P.map((p,i)=>`<div style="margin:8px 0"><label>${p[0]}: <b id="v${i}"></b></label><input type="range" min="0" max="100" step="1" data-i="${i}" style="width:100%"></div>`).join("")}<div id="bud" class="note"></div></div><div class="card" id="res"></div><p class="note">Illustrative model, not from the paper. Baseline prevalence is an approximate reading of Figure 1 (England 2007, men and women averaged). Assumes diminishing returns: each extra unit in one group averts fewer cases. It ignores cost differences, stigma, and the paper's warning that services for the poor often become poor services and are easily cut. Source: WHO &amp; Gulbenkian (2014), pp.17, 39.</p>`;
const upd=()=>{const s=A.reduce((a,b)=>a+b,0),rem=P.map((p,i)=>p[1]*Math.exp(-A[i]/K)),av=T-rem.reduce((a,b)=>a+b,0),before=P[4][1]/P[0][1],after=rem[4]/rem[0];
P.forEach((p,i)=>{E.querySelector("#v"+i).textContent=A[i].toFixed(1)+" units";E.querySelector(`[data-i="${i}"]`).value=A[i]});
E.querySelector("#bud").innerHTML=`Budget used: <b style="color:${s>100.5?"var(--bad)":"var(--ink)"}">${s.toFixed(1)}/100</b>${s>100.5?" (over budget)":""}`;
E.querySelector("#res").innerHTML=`<table><tr><th>Group</th><th>Cases per 100 before</th><th>After</th></tr>${P.map((p,i)=>`<tr><td>${p[0]}</td><td>${p[1].toFixed(1)}</td><td><div class="bar"><i style="width:${rem[i]/25*100}%"></i></div>${rem[i].toFixed(1)}</td></tr>`).join("")}</table><p><b>Cases averted:</b> ${av.toFixed(1)} of ${T.toFixed(1)} (${(av/T*100).toFixed(0)}%). <b>Lowest vs highest group after:</b> ${after.toFixed(2)}x (before: ${before.toFixed(2)}x).</p><p class="note">${(100*(T-P[4][1])/T).toFixed(0)}% of all cases at baseline sit outside the lowest-income group. Aim for a flat gradient (about 1.0x) with the most cases averted.</p>`};
E.querySelectorAll("[data-p]").forEach(b=>b.onclick=()=>{A=PRE[b.dataset.p].slice();upd()});
E.querySelectorAll("[data-i]").forEach(r=>r.oninput=()=>{A[+r.dataset.i]=+r.value;upd()});upd()}

function lib(){const L=window.INTV,u=i=>[...new Set(L.map(x=>x[i]))];
V.innerHTML=`<h2>Interventions library</h2><p class="mut">${L.length} case studies from the WHO report. Filter, then ask of each: could this work in my barangay? Who would deliver it, what would I adapt, and how would we measure mental health impact?</p><p><select id="fs"><option value="">All life stages</option>${u(2).map(x=>`<option>${x}</option>`).join("")}</select> <select id="fl"><option value="">All levels</option>${u(3).map(x=>`<option>${x}</option>`).join("")}</select> <input id="fq" placeholder="Search" style="padding:9px;border:1px solid var(--line);border-radius:8px;background:var(--card);color:var(--ink)"></p><div id="ll"></div><p class="note">Results are as reported in the paper (mostly from evaluations cited there); effect sizes were not independently verified and many come from other settings than the Philippines. Level "Workplace" is added by this app.</p>`;
const d=()=>{const s=$("#fs").value,l=$("#fl").value,q=$("#fq").value.toLowerCase(),r=L.filter(x=>(!s||x[2]===s)&&(!l||x[3]===l)&&(!q||x.join(" ").toLowerCase().includes(q)));
$("#ll").innerHTML=r.map(x=>`<details class="card"><summary><b>${esc(x[0])}</b> <span class="note">${esc(x[1])}</span></summary><p><span class="tag">${x[2]}</span> &middot; <span class="tag">${x[3]}</span></p><div class="tag">What</div><p>${esc(x[4])}</p><div class="tag">Reported results</div><p>${esc(x[5])}</p><div class="tag">RA 11036 hook</div><p>${esc(x[7])}</p><p class="note">WHO &amp; Gulbenkian (2014), ${esc(x[6])}</p></details>`).join("")||"<p>No matches.</p>"};
["fs","fl"].forEach(i=>$("#"+i).onchange=d);$("#fq").oninput=d;d()}

function comm(){const L=window.INTV;
const ST=[["Life course","Early-life adversity or neglect in the community"],["Family and household","Unemployment or insecure work"],["Family and household","Debt, including informal lending"],["Family and household","Parental mental illness or alcohol use"],["Family and household","Family or partner violence"],["Community","Violence, crime or low trust"],["Community","Flooding, crowding or poor built environment"],["Community","Isolated older people"],["Local services","No local mental health service or long travel"],["Local services","Schools without mental health programs"],["Local services","Unsafe water or sanitation"],["Country level","Weak social protection for informal workers"],["Country level","Stigma and discrimination"],["Country level","Disaster, conflict or displacement"]];
const GR=["Women","Children","Adolescents","Older people","People with mental disorders","Informal or unemployed workers","Geographically isolated residents","Disaster-affected or displaced"];
const TX=[["f_dist","1. Local distribution of mental disorders","What local data exist? Consider LGU quarterly reports (Sec. 17), RHU registers, school and barangay records."],["f_acc","2. Access and unmet need","How many people with mental disorders reach effective care? Barriers: distance, cost, stigma, workforce (Secs. 15, 16, 38)."],["f_ast","4. Local assets and resources","BHWs, churches, schools, livelihood groups, peer or self-help groups, existing programs."],["f_syn","7. Synergies and partners","Education, health, housing and built environment, transport, income, community development; multisectoral network (Sec. 37h)."],["f_ev","8. Measuring mental health impact","The WHO paper notes improvements are rarely monitored for mental health. What will you measure, how often, and who reviews it?"]];
let D={};try{D=JSON.parse(localStorage.getItem("mhComm")||"{}")}catch(e){}
V.innerHTML=`<h2>Community assessment worksheet</h2><p class="mut">Based on the WHO paper's "knowledge for action at the local level" (pp. 41-42). Ideally completed with community members. Do not enter patient-identifying information. Drafts save in this browser only.</p><div class="card"><input data-f="f_name" placeholder="Community / barangay" style="width:100%;padding:9px;margin:4px 0;box-sizing:border-box"><input data-f="f_pop" placeholder="Population and date" style="width:100%;padding:9px;margin:4px 0;box-sizing:border-box"></div>
${TX.slice(0,2).map(t=>`<div class="card"><h3>${t[1]}</h3><p class="note">${t[2]}</p><textarea data-f="${t[0]}" rows="3" style="width:100%;box-sizing:border-box"></textarea></div>`).join("")}
<div class="card"><h3>3. Social, economic and environmental stressors</h3><p class="note">Ideally identified by residents themselves (participatory). Tick all that apply.</p>${ST.map((s,i)=>`<label class="chk"><input type="checkbox" data-c="s${i}"><span><span class="tag">${s[0]}</span><br>${s[1]}</span></label>`).join("")}<input data-f="f_oth" placeholder="Other stressors named by the community" style="width:100%;padding:9px;margin-top:8px;box-sizing:border-box"></div>
<div class="card"><h3>${TX[2][1]}</h3><p class="note">${TX[2][2]}</p><textarea data-f="f_ast" rows="3" style="width:100%;box-sizing:border-box"></textarea></div>
<div class="card"><h3>5. Candidate interventions (from the library)</h3><p class="note">Match local assets to evidence from elsewhere.</p><details><summary>Choose interventions</summary>${L.map((x,i)=>`<label class="chk"><input type="checkbox" data-c="i${i}"><span>${esc(x[0])} <span class="note">(${esc(x[1])})</span></span></label>`).join("")}</details></div>
<div class="card"><h3>6. Equity check</h3><p class="note">Who might be affected differently by this initiative?</p>${GR.map((g,i)=>`<label class="chk"><input type="checkbox" data-c="g${i}"><span>${g}</span></label>`).join("")}<textarea data-f="f_eq" rows="3" placeholder="Could this widen or narrow gaps? How will effort scale with need, rather than reach only those below a cutoff?" style="width:100%;box-sizing:border-box;margin-top:8px"></textarea></div>
${TX.slice(3).map(t=>t[0]==="f_ast"?"":`<div class="card"><h3>${t[1]}</h3><p class="note">${t[2]}</p><textarea data-f="${t[0]}" rows="3" style="width:100%;box-sizing:border-box"></textarea></div>`).join("")}
<div class="card"><h3>Summary</h3><textarea id="sm" rows="14" style="width:100%;box-sizing:border-box"></textarea><p><button class="btn" id="cp">Copy</button> <button class="btn alt" id="pr">Print</button> <button class="btn alt" id="cl">Clear worksheet</button> <span id="ok" class="note"></span></p></div>`;
V.querySelectorAll("textarea[data-f],input[data-f]").forEach(e=>{if(D.f&&D.f[e.dataset.f])e.value=D.f[e.dataset.f]});
V.querySelectorAll("[data-c]").forEach(e=>{if(D.c&&D.c.includes(e.dataset.c))e.checked=true});
const g=k=>(V.querySelector(`[data-f="${k}"]`)||{}).value||"[ ]";
const ck=p=>[...V.querySelectorAll(`[data-c^="${p}"]:checked`)].map(e=>e.dataset.c.slice(1));
const up=()=>{const f={};V.querySelectorAll("[data-f]").forEach(e=>f[e.dataset.f]=e.value);const c=[...V.querySelectorAll("[data-c]:checked")].map(e=>e.dataset.c);try{localStorage.setItem("mhComm",JSON.stringify({f,c}))}catch(e){}
$("#sm").value=`COMMUNITY MENTAL HEALTH ASSESSMENT\n${g("f_name")} | ${g("f_pop")}\n\n1. Local distribution: ${g("f_dist")}\n2. Access and unmet need: ${g("f_acc")}\n3. Stressors: ${ck("s").map(i=>ST[i][1]).concat(g("f_oth")==="[ ]"?[]:[g("f_oth")]).join("; ")||"[none ticked]"}\n4. Assets: ${g("f_ast")}\n5. Candidate interventions: ${ck("i").map(i=>L[i][0]).join("; ")||"[none]"}\n6. Equity: groups to watch: ${ck("g").map(i=>GR[i]).join(", ")||"[none]"}. ${g("f_eq")}\n7. Synergies and partners: ${g("f_syn")}\n8. Evaluation: ${g("f_ev")}`};
V.oninput=up;up();
$("#cp").onclick=()=>navigator.clipboard.writeText($("#sm").value).then(()=>$("#ok").textContent="Copied",()=>{$("#sm").select();$("#ok").textContent="Select and copy manually"});
$("#pr").onclick=()=>window.print();
$("#cl").onclick=()=>{if(confirm("Clear this worksheet?")){try{localStorage.removeItem("mhComm")}catch(e){}comm()}}}


const dl=(t,h)=>`<div class="note">${t}</div>`;
function forms(m="ad"){
const F={ad:["Advance directive (Sec. 9)",[["name","Full name"],["date","Date"],["pref","Treatments I accept","t"],["ref","Treatments I refuse","t"],["med","Medicines that helped or harmed me","t"],["calm","What helps me calm in a crisis, and what to avoid (including my wishes about restraint)","t"],["fac","Preferred clinician or facility"],["con","People to contact in a crisis"],["rep","My legal representative, if any"]]],
rep:["Designation of legal representative (Sec. 10)",[["name","Full name"],["date","Date"],["rn","Representative's full name"],["rl","Relationship and contact details"],["lim","Instructions or limits for the representative","t"]]],
sup:["Supported decision making (Sec. 11)",[["name","Full name"],["date","Date"],["s1","Supporter 1: name and contact"],["s2","Supporter 2: name and contact"],["s3","Supporter 3: name and contact"]]]};
const f=F[m],g=k=>(V.querySelector(`[data-k="${k}"]`)||{}).value||"________";
V.innerHTML=`<h2>Directive, representative and supporter forms</h2><p class="mut">Drafting aids to review with the patient. Not legal advice. A directive and a designation must be signed, dated and notarized (Secs. 9-10); have the notary or a lawyer check the final form. Nothing is saved.</p>`+mode("fm",[["ad","Advance directive"],["rep","Legal representative"],["sup","Supporters"]],m)+`<div class="card"><h3>${f[0]}</h3>${f[1].map(x=>x[2]?`<label class="note">${x[1]}</label><textarea data-k="${x[0]}" rows="2" style="width:100%;box-sizing:border-box"></textarea>`:`<label class="note">${x[1]}</label><input data-k="${x[0]}" style="width:100%;padding:8px;margin-bottom:6px;box-sizing:border-box">`).join("")}</div><div class="card"><div id="doc" style="white-space:pre-wrap;font-size:15px"></div><p class="noprint"><button class="btn" id="cp">Copy</button> <button class="btn alt" id="pr">Print</button> <span id="ok" class="note"></span></p></div>`;wire("fm",forms);
const T={ad:()=>`ADVANCE DIRECTIVE\n(Republic Act No. 11036, Section 9)\n\nI, ${g("name")}, make this directive on ${g("date")} while I am able to decide for myself.\n\nTreatments I accept:\n${g("pref")}\n\nTreatments I refuse:\n${g("ref")}\n\nMedicines that have helped or harmed me:\n${g("med")}\n\nWhat helps me calm in a crisis, and what to avoid (including restraint):\n${g("calm")}\n\nPreferred clinician or facility: ${g("fac")}\nPeople to contact: ${g("con")}\nMy legal representative: ${g("rep")}\n\nI understand that, if I am in a psychiatric emergency or temporarily unable to decide, my treating team will follow this directive unless doing so would pose an immediate risk of serious harm to me or another person (Section 13a). I may revoke it by a new advance directive or a notarized revocation.\n\nSignature: ______________________   Date: ____________\n\nACKNOWLEDGMENT BEFORE A NOTARY PUBLIC\n[To be completed by the notary. Notarization is required.]`,
rep:()=>`DESIGNATION OF LEGAL REPRESENTATIVE\n(Republic Act No. 11036, Section 10)\n\nI, ${g("name")}, designate ${g("rn")} (${g("rl")}) of legal age as my legal representative on ${g("date")}.\n\nMy representative may: (1) support and help me, represent my interests and receive medical information about me as the Act allows; (2) act as substitute decision maker only when a mental health professional has assessed that my decision-making capacity is temporarily impaired; (3) help me exercise my rights under the Act; and (4) be consulted on any treatment or therapy I receive.\n\nInstructions or limits: ${g("lim")}\n\nI may revoke this designation by appointing a new representative or by a notarized revocation.\n\nSignature of service user: ______________________\n\nRepresentative's acceptance: ______________________   (A representative may decline, but must take reasonable steps to inform me and my attending professional.)\n\nNOTARIAL ACKNOWLEDGMENT\n[Notarization is required.]`,
sup:()=>`DESIGNATION OF SUPPORTERS\n(Republic Act No. 11036, Section 11)\n\nI, ${g("name")}, designate up to three supporters on ${g("date")}:\n1. ${g("s1")}\n2. ${g("s2")}\n3. ${g("s3")}\n\nMy supporters may access my medical information, consult with me about any proposed treatment or therapy, and be present at my appointments and consultations.\n\nThe decision remains mine. Supporters help me express my preferences; they do not decide for me.\n\nSignature: ______________________   Date: ____________\n\n[The Act does not prescribe a form for supporters. File a copy in the chart and check your institution's policy and the IRR.]`};
const up=()=>{$("#doc").textContent=T[m]()};V.oninput=up;up();
$("#cp").onclick=()=>navigator.clipboard.writeText($("#doc").textContent).then(()=>$("#ok").textContent="Copied",()=>$("#ok").textContent="Select the text and copy manually");
$("#pr").onclick=()=>{document.body.classList.add("pd");window.print();document.body.classList.remove("pd")}}

function viol(){const L=shuffle(window.VIOL.map(x=>x)),O=["Sec. 44(a): no informed consent","Sec. 44(b): confidentiality breach","Sec. 44(c): discrimination","Sec. 44(d): inhumane or unscientific treatment","Rights breach not listed in Sec. 44","No violation"];let n=0,sc=0;
V.innerHTML=`<h2>Spot the violation</h2><p class="mut">Sec. 44 penalty: 6 months to 2 years, or P10,000 to P200,000, or both. Which offence, if any, does each scenario describe?</p><div id="vq"></div>`;
const r=()=>{const q=$("#vq");if(n>=L.length){q.innerHTML=`<div class="card"><h3>Score ${sc}/${L.length}</h3><button class="btn" id="ag">Again</button></div>`;$("#ag").onclick=viol;return}
const s=L[n];q.innerHTML=`<div class="card"><div class="tag">${n+1}/${L.length}</div><h3>${esc(s[0])}</h3>${O.map((o,i)=>`<button class="opt" data-i="${i}">${o}</button>`).join("")}<div id="fb"></div></div>`;
document.querySelectorAll(".opt").forEach(b=>b.onclick=()=>{const i=+b.dataset.i;document.querySelectorAll(".opt").forEach(o=>{o.disabled=true;if(+o.dataset.i===s[1])o.classList.add("ok")});if(i===s[1])sc++;else b.classList.add("no");$("#fb").innerHTML=`<div class="fb">${esc(s[2])}</div><p><button class="btn" id="nx">Next</button></p>`;$("#nx").onclick=()=>{n++;r()}})};r()}

function audit(){const A=window.AUDIT;
V.innerHTML=`<h2>Facility self-audit for rotations</h2><p class="mut">Tick what is in place at your rotation site. Unticked items become your questions for the consultant, IRB or administrator. Nothing is saved.</p><div class="card"><input id="fn" placeholder="Facility (optional)" style="width:100%;padding:9px;box-sizing:border-box"></div>${A.map((g,gi)=>`<div class="card"><h3>${g.g}</h3>${g.i.map((x,i)=>`<label class="chk"><input type="checkbox" data-g="${gi}" data-i="${i}"><span>${x[0]} <span class="note">(${x[1]})</span></span></label>`).join("")}<div class="note" id="s${gi}"></div></div>`).join("")}<div class="card"><h3>Summary</h3><div id="au"></div><textarea id="at" rows="8" style="width:100%;box-sizing:border-box"></textarea><p><button class="btn" id="cp">Copy</button> <span id="ok" class="note"></span></p></div>`;
const up=()=>{let t=0,d=0,gaps=[];A.forEach((g,gi)=>{let c=0;g.i.forEach((x,i)=>{const on=V.querySelector(`[data-g="${gi}"][data-i="${i}"]`).checked;if(on)c++;else gaps.push(`${x[0]} (${x[1]})`)});$("#s"+gi).textContent=c+"/"+g.i.length+" in place";t+=g.i.length;d+=c});
$("#au").innerHTML=`<div class="stat">${d}/${t}</div>items in place`;
$("#at").value=`FACILITY SELF-AUDIT (RA 11036): ${$("#fn").value||"[facility]"}\n${d}/${t} items in place.\n\nQuestions to raise:\n`+(gaps.map(x=>"- "+x).join("\n")||"- None")};
V.oninput=up;up();$("#cp").onclick=()=>navigator.clipboard.writeText($("#at").value).then(()=>$("#ok").textContent="Copied",()=>$("#ok").textContent="Select and copy manually")}

function rights(m="say"){
const SAY=`These are your rights while you are in our care (RA 11036, Sec. 5):\n- You will not be discriminated against or shamed because of your condition.\n- You will get evidence-based treatment of the same quality as anyone else.\n- We need your written consent for treatment, and you can withdraw it. Exceptions are only for emergencies or when you cannot decide, and then only with safeguards and review.\n- You can help write your treatment plan, choose a legal representative, and name up to three supporters.\n- Your information is confidential, except in the few cases the law allows.\n- You will be treated humanely: no torture, cruel or degrading treatment, no unscientific procedures, no solitary confinement.\n- You can send and receive private messages and have visitors at reasonable times, including a lawyer and the Commission on Human Rights.\n- You can see your records, unless your doctor believes it would harm you or others; you can contest that.\n- You can have a lawyer; the Public Attorney's Office can help if you cannot pay.\n- You can complain, yourself or through a representative.\n\nAsk the person to say back one right in their own words. Record in the chart: time, language used, and who was present (within 24 hours of admission, Sec. 5s).`;
const R=[["I was treated or restrained without consent","Internal review board (IRB): the user, immediate family or legal representative may file a written complaint; the IRB investigates and can recommend administrative, civil or criminal action (Sec. 12b). CHR: investigates involuntary treatment and confinement; may act on its own initiative (Secs. 31, 33). DOH and DOJ also receive complaints (Sec. 33). Legal help: Public Attorney's Office (Sec. 5q). Possible offence: Sec. 44(a)."],["My records are being withheld","Records may be withheld only if disclosure would harm the user or endanger others. The user or representative may contest with the IRB or the CHR (Sec. 5r)."],["My information was disclosed","Complain to the IRB, CHR or DOH (Secs. 12, 31, 33). Possible offence: Sec. 44(b). Sec. 5(l) lists the only exceptions."],["Discrimination at work or school","Sec. 5(a)-(b) guarantees freedom from discrimination. DOLE/CSC and DepEd/CHED/TESDA must develop policies against stigma (Secs. 34-35). Possible offence: Sec. 44(c); seek legal aid (Sec. 5q)."],["Facility conditions are cruel, unsafe or degrading","IRB inspects facilities (Sec. 12b2); CHR inspects (Secs. 31b, 33); DOH licenses and monitors facilities (Sec. 30b). Possible offence: Sec. 44(d)."]];
const H=["Tell your consultant or department head and hospital counsel or the IRB promptly.","Do not alter, add to or backdate chart entries. Preserve records.","Disclose chart contents only as far as needed to resolve the case (Sec. 5l-5), and through counsel.","Cooperate with IRB, CHR and DOH inspections and investigations (Secs. 12, 31, 33).","Check whether the Sec. 13 safeguards were documented: order, necessity, IRB review dates.","Where appropriate, speak with the patient and family and learn from what happened.","Seek support: professionals have the right to a safe and supportive work environment (Sec. 7a)."];
V.innerHTML=`<h2>Rights and complaints</h2>`+mode("rm",[["say","Explaining rights"],["where","Where to complain"],["resp","If you are complained about"]],m)+`<div id="rv3"></div>`;wire("rm",rights);const E=$("#rv3");
if(m==="say"){E.innerHTML=`<div class="card"><div style="white-space:pre-wrap">${esc(SAY)}</div><p><button class="btn" id="cp">Copy script</button> <span id="ok" class="note"></span></p></div><p class="note">Plain-language adaptation of Sec. 5. Translate into the patient's language; keep the 24-hour rule (Sec. 5s).</p>`;$("#cp").onclick=()=>navigator.clipboard.writeText(SAY).then(()=>$("#ok").textContent="Copied",()=>$("#ok").textContent="Select and copy manually")}
else if(m==="where"){E.innerHTML=`<div class="card"><label>Situation: <select id="sx"><option value="">Choose</option>${R.map((x,i)=>`<option value="${i}">${x[0]}</option>`).join("")}</select></label><div id="sr" class="fb" style="display:none"></div></div><p class="note">The CHR's investigative role is limited to civil and political rights (Sec. 32). Sec. 44 penalties require conviction by final judgment.</p>`;$("#sx").onchange=e=>{const x=R[e.target.value];$("#sr").style.display=x?"block":"none";if(x)$("#sr").textContent=x[1]}}
else E.innerHTML=`<div class="card"><ol>${H.map(x=>`<li>${x}</li>`).join("")}</ol></div><p class="note">General professional practice anchored to the Act where cited; follow your institution's policy and seek advice from counsel.</p>`}

function glossary(){
 const terms=window.GLOSSARY||[];
 V.innerHTML=`<h2>Glossary of terms</h2><p class="mut">Plain-language study definitions drawn from RA 11036 and the WHO &amp; Calouste Gulbenkian Foundation report <i>Social Determinants of Mental Health</i> (2014). Select a source reference to open the Act section where available.</p><input id="gq" aria-label="Search glossary" placeholder="Search a term or definition…" style="width:100%;margin:8px 0 14px"><div id="glossary-list"></div><p class="note">Definitions are learning aids, not substitutes for the Act's wording or clinical guidance. WHO page references refer to the 2014 report.</p>`;
 const draw=q=>{q=q.toLowerCase().trim();const rows=terms.filter(t=>!q||(t.term+' '+t.definition+' '+t.tags.join(' ')).toLowerCase().includes(q));$('#glossary-list').innerHTML=rows.length?rows.map(t=>`<article class="card glossary-item"><h3>${esc(t.term)}</h3><p>${esc(t.definition)}</p><div class="glossary-meta">${t.sources.map(src=>src.kind==='act'?`<a class="act-link source-link" href="#law" data-act-ref="${src.ref}" title="Open ${esc(src.label)} in The Act">${esc(src.label)} ↗</a>`:`<span class="source-chip">${esc(src.label)}</span>`).join(' · ')}</div></article>`).join(''):'<p class="mut">No glossary matches. Try another word.</p>'};
 $('#gq').oninput=e=>draw(e.target.value);draw('');
}
function openActReference(ref){
 const n=String(ref||'').match(/\d+/);if(!n)return;go('law');
 const search=$('#lq');if(search)search.value='';
 const query=$('#lw');if(!query)return;
 query.querySelectorAll('details').forEach(d=>d.open=false);
 let target=query.querySelector(`#act-sec-${CSS.escape(n[0])}`);
 if(!target){const roman=String(ref).match(/chapter\s*([ivx]+)/i);if(roman)target=query.querySelector(`#act-chapter-${roman[1].toUpperCase()}`)}
 if(target){if(target.tagName.toLowerCase()==='details')target.open=true;target.classList.add('act-target-highlight');target.scrollIntoView({behavior:'smooth',block:'center'});setTimeout(()=>target.classList.remove('act-target-highlight'),1800)}
}
// Automatically turn legal references in learning content into links to the Act browser.
function linkifyActReferences(rootEl){
 if(!rootEl)return;const walker=document.createTreeWalker(rootEl,NodeFilter.SHOW_TEXT,{acceptNode(node){const p=node.parentElement;if(!p||!node.nodeValue.trim())return NodeFilter.FILTER_REJECT;if(p.closest('a,button,script,style,textarea,input,select,summary,details,code,pre,.act-link,.no-act-link,#lw'))return NodeFilter.FILTER_REJECT;if(!/\b(?:sec(?:tion)?s?\.?|chapters?)\s+(?:\d+|[ivx]+)\b/i.test(node.nodeValue))return NodeFilter.FILTER_REJECT;return NodeFilter.FILTER_ACCEPT}});
 const nodes=[];while(walker.nextNode())nodes.push(walker.currentNode);
 const re=/\b((?:Secs?\.?|Sections?)\s+(\d+)(?:\s*\([a-z]\))?(?:\s*[-–]\s*\d+)?|((?:Chapter)\s+([IVX]+|\d+)))\b/gi;
 for(const node of nodes){const text=node.nodeValue;re.lastIndex=0;let m,last=0,frag=document.createDocumentFragment(),found=false;while((m=re.exec(text))){if(m.index>last)frag.append(document.createTextNode(text.slice(last,m.index)));const a=document.createElement('a');a.className='act-link';a.href='#law';a.textContent=m[1];a.setAttribute('data-act-ref',m[2]||('chapter '+m[4]));a.title='Open this reference in The Act';frag.append(a);last=re.lastIndex;found=true}if(found){if(last<text.length)frag.append(document.createTextNode(text.slice(last)));node.parentNode.replaceChild(frag,node)}}
}
V.addEventListener('click',e=>{const a=e.target.closest('a.act-link[data-act-ref]');if(!a)return;e.preventDefault();const ref=a.dataset.actRef;if(/^chapter/i.test(ref)){go('law');const card=$(`#act-chapter-${ref.replace(/^chapter\s*/i,'').toUpperCase()}`);if(card)card.scrollIntoView({behavior:'smooth',block:'center'});}else openActReference(ref)});
const linkObserver=new MutationObserver(()=>linkifyActReferences(V));linkObserver.observe(V,{childList:true,subtree:true});
go(Object.keys(names).includes(location.hash.slice(1))?location.hash.slice(1):"home");
if("serviceWorker"in navigator&&location.protocol.startsWith("http"))navigator.serviceWorker.register("sw.js").catch(()=>{})})();
