// Content derived from RA 11036 (Supreme Court E-Library text) and WHO & Calouste Gulbenkian Foundation (2014), Social Determinants of Mental Health.
// Review all clinical/legal content against the current IRR and your institution's policies before use.
window.DATA={
quiz:[
{t:"Capacity",q:"A man with schizophrenia is brought for a medication review. What is the legal starting point on his capacity?",o:["Presumed to lack capacity until assessed","Presumed to have legal capacity","Family decides until stable","Capacity is decided by the facility head"],a:1,e:"Sec. 8: all persons, including service users, persons with disabilities and minors, are presumed to have legal capacity irrespective of their condition."},
{t:"Capacity",q:"Which is NOT one of the four inabilities that define impairment or temporary loss of decision-making capacity (Sec. 4g)?",o:["Understanding the nature of the mental health condition","Understanding consequences of one's decisions","Agreeing with the clinician's recommendation","Communicating consent or information about one's condition"],a:2,e:"Capacity concerns understanding and communicating, not agreement. Refusing a recommendation is not evidence of incapacity."},
{t:"Consent",q:"Does chemical restraint require informed consent under the Act?",o:["No, it is a medicine","Only for minors","Yes, unless the Sec. 13 exceptions and safeguards apply","Only if a relative objects"],a:2,e:"Sec. 8 requires written informed consent before any plan of treatment 'including physical or chemical restraint'. Sec. 13 gives the exceptions."},
{t:"Involuntary care",q:"A restraint order is issued on Day 0. When must the IRB first review it?",o:["Within 24 hours","Within 72 hours","Within 15 days, then every 15 days","Only if the family complains"],a:2,e:"Sec. 13(c): review by the facility's internal review board within 15 days of the order, and every 15 days while it continues."},
{t:"Involuntary care",q:"Which is NOT a Sec. 13 safeguard for treatment or restraint without consent?",o:["Follow the advance directive unless it poses immediate risk of serious harm","Only as necessary and only while the emergency or incapacity lasts","Order by the attending mental health professional","Written approval of the legal representative before any order"],a:3,e:"Sec. 13(a)-(d) lists advance directive, necessity and duration, attending MHP order with IRB review, and guideline-based, documented, audited practice."},
{t:"Representation",q:"No legal representative has been designated. Who is first in the default order (Sec. 10c)?",o:["Eldest sibling","Spouse (unless permanently separated by decree or abandonment)","Parent","Facility head"],a:1,e:"Order: spouse; non-minor children; either parent by mutual consent if a minor; facility chief/administrator/medical director; court appointee. Siblings are not listed."},
{t:"Rights",q:"Within what time must service users be told their rights after admission to a mental health facility?",o:["6 hours","24 hours","48 hours","7 days"],a:1,e:"Sec. 5(s): within 24 hours of admission, in a form and language the person understands."},
{t:"Advance directive",q:"What makes an advance directive valid under Sec. 9?",o:["Verbal statement to a nurse","Signed, dated and notarized","Countersigned by a psychiatrist","Approved by the IRB"],a:1,e:"It may be revoked by a new directive or by a notarized revocation."},
{t:"Confidentiality",q:"A 15-year-old discloses that her stepfather beats her. Which confidentiality exception applies?",o:["None; she asked for secrecy","The minor is reasonably believed to be a victim of child abuse (Sec. 5l-4)","Only with her mother's consent","Only a court order"],a:1,e:"You cannot promise secrecy. Explain honestly what will be shared and with whom, and involve her in the plan (Sec. 8: children's views get due consideration)."},
{t:"Supported decisions",q:"How many supporters may a service user designate for supported decision making (Sec. 11)?",o:["One","Two","Up to three","As many as the family wishes"],a:2,e:"Supporters may access medical information, consult on treatment and attend appointments. The decision stays with the person."},
{t:"Penalties",q:"Which range matches the Sec. 44 penalty?",o:["Fine of P1,000 to P5,000 only","6 months to 2 years, or P10,000 to P200,000, or both","1 to 5 years only","P500,000 fine only"],a:1,e:"Applies to failure to secure consent outside Sec. 13, breach of confidentiality, discrimination, and inhumane or unscientific treatment."},
{t:"Systems",q:"Which Act provision lets geographically isolated areas receive services through home visits or mobile clinics?",o:["Sec. 16","Sec. 21","Sec. 38","Sec. 43"],a:2,e:"Sec. 38: people in geographically isolated and highly populated, depressed areas shall have the same level of access."},
{t:"Systems",q:"Which data must LGU quarterly reports include (Sec. 17), without identifying patients?",o:["Only diagnosis counts","Numbers served, conditions, treatment duration and result, age, gender, educational attainment and employment","Only suicide counts","Household income and religion"],a:1,e:"Educational attainment and employment make Sec. 17 reports a social-determinants data source."},
{t:"Social determinants",q:"What did the WHO report cite for 115 LMIC studies on poverty and common mental disorders?",o:["Under 10% found a link","Over 70% reported positive associations","No consistent pattern","Link only for men"],a:1,e:"WHO & Gulbenkian (2014), p.16, citing Lund et al. 2010. Strength varied by poverty measure."},
{t:"Social determinants",q:"In the Jenkins et al. British study, what was the finding on debt?",o:["Debt had no effect after income adjustment","More debt meant higher likelihood of mental disorder even after adjusting for income","Debt only mattered for the unemployed","Debt protected mental health"],a:1,e:"Ask about debt, not only income. In Philippine practice this includes informal lending."},
{t:"Social determinants",q:"What does 'proportionate universalism' mean?",o:["Services only for the poorest","Equal services for all regardless of need","Universal actions, scaled in intensity to level of disadvantage","Private-sector provision"],a:2,e:"Targeting only the most disadvantaged will not flatten the social gradient, and targeted services often decay."},
{t:"Social determinants",q:"Estimated prevalence of common perinatal mental disorders in LMIC women (WHO report, p.19)?",o:["About 2% antenatal, 4% postnatal","About 16% antenatal, 20% postnatal","About 40% in both","Not measurable"],a:1,e:"Risk factors include IPV, lack of partner support, unintended pregnancy and socioeconomic disadvantage."},
{t:"Social determinants",q:"Why does the WHO paper stress early childhood?",o:["Later action has no effect","Consensus that a best possible start yields the greatest societal and mental health benefit","It is cheaper than treatment only","Only parents matter"],a:1,e:"Comprehensive action across the life course is still needed. Disadvantage starts before birth and accumulates."}
],
cards:[
["Sec. 4(j): mental health","A state of well-being: realizes abilities, copes with normal stress, shows resilience in extreme life events, works productively, contributes to community."],
["Sec. 4(r): psychosocial problem","Dysfunction in behavior, thoughts and feelings from sudden, extreme, prolonged or cumulative stressors in the physical or social environment."],
["Sec. 4(q): psychiatric or neurologic emergency","Serious and immediate threat to the health and well-being of the service user or others requiring immediate medical intervention."],
["Sec. 4(p): mental health worker","Trained person, volunteer or advocate providing support under the supervision of a mental health professional (includes trained BHWs)."],
["Sec. 4(v): supported decision making","Assisting a service user WITHOUT impaired capacity to express preferences, with safeguards against undue influence, coercion or abuse."],
["Sec. 5(l): five confidentiality exceptions","Law or court order; user's consent; life-threatening emergency; suspected child abuse of a minor; case against an MH professional or worker for negligence or ethics breach."],
["Sec. 8","Written informed consent before any treatment plan, including physical or chemical restraint. Everyone is presumed to have legal capacity. Children's views get due consideration."],
["Sec. 9: advance directive","Signed, dated, notarized. Revoked by a new directive or a notarized revocation."],
["Sec. 10(c): default legal representative","Spouse; non-minor children; either parent (minor); facility chief/administrator/medical director; court appointee."],
["Sec. 12: IRB","Every public and private facility. DOH rep, CHR rep, nominee of an accredited service-user/family organization, others per IRR. Reviews, audits, inspects, investigates, remedies."],
["Sec. 13: four safeguards","(a) advance directive; (b) only as needed, only while it lasts; (c) attending MHP order, IRB review within 15 days then every 15 days; (d) approved guidelines, documented, audited."],
["Sec. 14","Services must be evidence-based, responsive to clinical, gender, cultural and ethnic needs, in the least restrictive setting, age appropriate, accountable."],
["Sec. 18","Regional, provincial and tertiary hospitals (incl. private): short-stay ward, partial hospital care, outpatient, home care, addiction coordination, referral system."],
["Sec. 19","Facilities: minimize restrictive care, inform rights, disclose treatment plan, obtain consent, keep a treatment register, legal representatives only by proper procedure."],
["Sec. 21: suicide prevention","Intervention, prevention and response strategies with attention to youth; 24/7 hotlines set up and strengthened."],
["Sec. 44: penalties","6 months to 2 years, or P10,000 to P200,000, or both: no consent, confidentiality breach, discrimination, inhumane or unscientific treatment."],
["Social gradient","Common mental disorders are distributed along a gradient of economic disadvantage, not just a poor/non-poor cliff."],
["Stress-buffering model","Exposure to stressors, buffers (support, coping), biology, accumulation over life, outcome. Every intervention reduces exposure or strengthens buffers."],
["Multilevel framework (WHO)","Life course; parents, families and households; community; local services; country-level factors."],
["Two-way poverty cycle","Poverty raises risk; mental disorder lowers income and employment, deepening poverty."]
],
cases:[
{title:"Mario, 32: the emergency room",intro:"Jeepney driver brought by barangay tanods. No sleep for five days, believes neighbors poison his food, shouting at staff, refuses medication. Lost his route three months ago; owes an informal lender. Wife is with him.",steps:[
{q:"First move?",o:[["Restrain and medicate now; the wife will consent later",0,"Restraint or chemical restraint needs consent or the Sec. 13 conditions. Less restrictive options come first (Sec. 14c, 19a)."],["De-escalate, involve wife as supporter, offer voluntary oral medication, assess safety",1,"Right. Least restrictive care first, with a trusted supporter."],["Discharge since he refuses",0,"Refusal alone does not end your duty; assess capacity and risk."]]},
{q:"He still refuses and is dangerous to others. What allows treatment without consent?",o:[["Wife's verbal agreement",0,"Substitute consent requires assessed capacity impairment; wife's role is as default representative (Sec. 10c-1) only then."],["Emergency or assessed temporary loss of capacity, with all four Sec. 13 safeguards",1,"Right: as needed only, attending MHP order, IRB review within 15 days then every 15, documented per guidelines."],["The tanods' request",0,"Tanods have no authority to consent."]]},
{q:"Which actions also protect against readmission?",o:[["Document capacity findings and rights explained within 24 hours; advance directive discussion before discharge",1,"Yes (Secs. 5s, 9)."],["Refer to MSWDO/DOLE/LGU livelihood and address informal debt; BHW home follow-up; carer psychoeducation (Secs. 6a, 36, 37)",1,"Yes. Job loss and debt are active stressors (WHO: debt and unemployment raise risk). Document social needs with Z codes."],["Tell neighbors and tanods his diagnosis so they can watch him",0,"Breach of confidentiality (Sec. 5l; penalty Sec. 44b)."]],multi:true}]},
{title:"Joy, 15: the rural health unit",intro:"Headaches and falling grades. After time with the nurse she says her stepfather hits her when he drinks and she feels hopeless. She begs you not to tell her mother, who works abroad.",steps:[
{q:"How do you handle her request for secrecy?",o:[["Promise secrecy to keep trust",0,"You cannot promise: suspected child abuse is a Sec. 5(l)(4) exception."],["Explain honestly what must be shared and with whom, and involve her in the plan",1,"Right. Her views get due weight (Sec. 8)."],["Tell the stepfather what she said",0,"This endangers her and breaches confidentiality."]]},
{q:"What assessment is needed today?",o:[["Safety at home, depressive symptoms and suicide risk (ask directly), alcohol use at home",1,"Sec. 21 and general practice: asking about suicide does not plant the idea; do not leave her alone if risk is imminent."],["Only a headache workup",0,"Misses the psychosocial picture."],["None; refer next month",0,"Delay increases risk."]]},
{q:"Which determinants should the plan address?",o:[["Parental migration and care arrangements; family violence; alcohol in the household; school support",1,"Multilevel framework: household, community, local services. Link to MSWDO/child protection, school (Sec. 24), and follow-up."],["Only her grades",0,"Grades are a symptom of broader stressors."],["None are modifiable",0,"WHO evidence: parenting and family support and school programs are effective."]]}]},
{title:"Aling Nena, 72: barangay home visit",intro:"Widow living alone, children abroad. A BHW notes poor appetite, withdrawal and no longer attending church. No diagnosis.",steps:[
{q:"What is the BHW's role?",o:[["Diagnose depression and start medication",0,"BHWs act under supervision of a mental health professional (Sec. 4p); they identify early and refer."],["Early identification, supportive visit, refer to RHU, arrange follow-up",1,"Right (Secs. 15, 16, 27)."],["Do nothing without a diagnosis",0,"A psychosocial problem or sub-threshold distress still matters (Sec. 4r)."]]},
{q:"Which social determinant is most relevant?",o:[["Social isolation, bereavement, living alone",1,"WHO report: isolation is a strong risk factor in older age, especially for women."],["Only age",0,"Age alone does not explain risk; conditions of daily life do."],["Unrelated to mental health",0,"Contradicts the evidence."]]},
{q:"Which actions have supporting evidence?",o:[["Befriending and social activity, volunteering, community programs, physical activity, heating or housing improvement",1,"Examples cited in the WHO report. Evidence for LMIC older adults is notably limited, so evaluate locally."],["Isolating her for safety",0,"Increases harm."],["Ignoring until she asks for help",0,"Help-seeking is limited by hiya and stigma."]]}]}
],
screen:[
{d:"Economic stability",ask:"Enough income for food and bills? Any debt, including informal lending ('5-6')?",z:"Z59.x (housing/economic circumstances); Z56.x (employment)",r:"MSWDO/DSWD (Sec. 36); LGU livelihood (Sec. 37f); DOLE"},
{d:"Employment",ask:"Job loss, short-term contracts, unsafe or low-control work?",z:"Z56.x",r:"DOLE/CSC (Sec. 35); employer program (Sec. 25)"},
{d:"Education",ask:"Schooling interrupted? Able to read health information?",z:"Z55.x",r:"School counselor; DepEd/CHED/TESDA (Sec. 34)"},
{d:"Housing and environment",ask:"Crowding, eviction risk, unsafe housing, no clean water or sanitation, recent disaster?",z:"Z59.x",r:"LGU housing (Sec. 37f); DSWD disaster psychosocial support (Sec. 36c)"},
{d:"Safety and violence",ask:"Do you feel safe at home and in your community? Anyone hurting you?",z:"Z63.x (family), Z65.x (psychosocial)",r:"Child or women protection services; PAO (Sec. 5q); CHR (Sec. 31)"},
{d:"Social support",ask:"Who can you count on? Living alone? Feeling isolated?",z:"Z60.x (social environment)",r:"Community groups, peer support, befriending, family carers (Sec. 6)"},
{d:"Access to care",ask:"Distance, travel cost or stigma delaying care? Any cultural or traditional care you use?",z:"Z75.x (health services access)",r:"Home visits or mobile clinic (Sec. 38); BHW link (Sec. 27)"},
{d:"Migration and family separation",ask:"Is a parent or partner working abroad? Who cares for the children?",z:"Z63.x",r:"MSWDO; school; family support"}
],
ref:[
["2","Policy","Five State commitments; CRPD and UDHR; Magna Carta for PWDs applies"],
["3","Objectives","Six objectives: governance, integrated system, rights, information, basic services, promotion in schools/work/communities"],
["4","Definitions","Capacity (g), informed consent (h), mental health (j), emergency (q), psychosocial problem (r), supported decision making (v)"],
["5","User rights","Non-discrimination, equal quality, humane care, confidentiality (l), consent (m), rights within 24h (s), complaints (t)"],
["6-7","Carers and professionals","Carers: support, plan participation, release/transfer. Professionals: safe work, training, advocate for user (7g)"],
["8","Consent","Written consent incl. restraint; presumed legal capacity; children's views"],
["9-11","Directive, representative, supporters","Notarized directive; default order of representatives; up to 3 supporters"],
["12-13","IRB, exceptions","IRB composition and powers; four safeguards; 15-day review"],
["14-22","Services","Quality, community level, facilities, drug screening, suicide prevention, public awareness"],
["23-25","Education and work","Curriculum, school programs and professionals, workplace policies"],
["26-29","Capacity building, research, NCMH","Training, BHW training (27), research, NCMH"],
["30-38","Agency duties","DOH, CHR, DepEd/CHED/TESDA, DOLE/CSC, DSWD, LGUs; isolated-area access (38)"],
["39-42","Council","Philippine Council for Mental Health, DOH Mental Health Division"],
["43-44","Drugs, penalties","Drug dependents examined for MH conditions; 6 mo to 2 yr and/or P10,000-P200,000"]
]};
