// Flashcards derived strictly from RA 11036 and WHO & Calouste Gulbenkian Foundation (2014), Social Determinants of Mental Health.
window.FLASHCARDS={
  ra:[
    ["RA 11036 — Sec. 4(j): Mental health","A state of well-being in which a person realizes abilities, copes with normal stresses, works productively, and contributes to the community."],
    ["RA 11036 — Sec. 4(r): Psychosocial problem","Dysfunction in behavior, thoughts and feelings resulting from sudden, extreme, prolonged or cumulative stressors in the physical or social environment."],
    ["RA 11036 — Sec. 4(q): Psychiatric or neurologic emergency","A serious and immediate threat to the health and well-being of the service user or others that requires immediate medical intervention."],
    ["RA 11036 — Sec. 4(p): Mental health worker","A trained person, volunteer or advocate providing support under the supervision of a mental health professional; the definition includes trained barangay health workers."],
    ["RA 11036 — Sec. 4(v): Supported decision-making","Assistance for a service user who does not have impaired capacity to express preferences, with safeguards against undue influence, coercion or abuse."],
    ["RA 11036 — Sec. 4(g): Impaired decision-making capacity","The Act describes capacity in terms of the ability to understand the nature of the mental health condition, consequences of decisions, the proposed intervention, and to communicate consent or information."],
    ["RA 11036 — Sec. 5: Core rights","The Act sets out rights including non-discrimination, equal access to quality care, humane treatment, confidentiality, informed consent, information about rights, and a complaints process."],
    ["RA 11036 — Sec. 5(l): Confidentiality exceptions","The Act identifies exceptions including the service user's consent, a law or court order, a life-threatening emergency, suspected child abuse of a minor, and a case against a mental health professional or worker for negligence or an ethics breach."],
    ["RA 11036 — Sec. 5(s): When must rights be explained?","Within 24 hours of admission to a mental health facility, in a form and language the service user understands."],
    ["RA 11036 — Sec. 8: Informed consent","Written informed consent is required before a treatment plan, including physical or chemical restraint, subject to the Act's specific Sec. 13 exceptions and safeguards."],
    ["RA 11036 — Sec. 8: Presumption of capacity","All persons, including service users, persons with disabilities and minors, are presumed to have legal capacity irrespective of their condition."],
    ["RA 11036 — Sec. 8: Children's views","The views of children must be given due consideration in decisions affecting them, according to their age and maturity."],
    ["RA 11036 — Sec. 9: Advance directive requirements","An advance directive must be signed, dated and notarized. It may be revoked by a new directive or by a notarized revocation."],
    ["RA 11036 — Sec. 10(c): Default legal representative","The statutory order begins with spouse; non-minor children; either parent by mutual consent for a minor; facility chief/administrator/medical director; and a court appointee, subject to the Act's conditions."],
    ["RA 11036 — Sec. 11: Supporters","A service user may designate up to three supporters for supported decision-making. Support does not transfer the person's decision to the supporter."],
    ["RA 11036 — Sec. 12: Internal Review Board (IRB)","Mental health facilities must have an IRB. The Act sets out its composition and functions, including review, audit, inspection, investigation and recommending remedies."],
    ["RA 11036 — Sec. 13(a): Advance directive safeguard","When treatment, restraint or confinement without consent is considered, the advance directive must be checked and followed unless the Act's immediate serious-harm exception applies."],
    ["RA 11036 — Sec. 13(b): Necessity and duration","An intervention without consent must be limited to what is necessary and must not continue beyond the period when the emergency or impaired/temporarily lost capacity persists."],
    ["RA 11036 — Sec. 13(c): Order and review","The attending mental health professional issues the order. The facility IRB reviews it within 15 days and every 15 days while it continues."],
    ["RA 11036 — Sec. 13(d): Documentation and oversight","The intervention must follow approved facility guidelines, be documented, and be open to independent monitoring, review and audit."],
    ["RA 11036 — Sec. 14: Service principles","Mental health services should be evidence-based, responsive to clinical, gender, cultural and ethnic needs, age-appropriate, accountable, and provided in the least restrictive setting."],
    ["RA 11036 — Sec. 15: Community-based services","The Act provides for community-level mental health services as part of the mental health service system."],
    ["RA 11036 — Sec. 17: LGU reporting","Quarterly reports include aggregate information such as numbers served, conditions, treatment duration and results, age, gender, educational attainment and employment; reports should not identify patients."],
    ["RA 11036 — Sec. 18: Hospital services","Regional, provincial and tertiary hospitals are to provide mental health services including short-stay ward, partial hospital care, outpatient and home care, addiction coordination and referral systems."],
    ["RA 11036 — Sec. 19: Facility duties","Facilities must minimize restrictive care, inform users of rights, disclose the treatment plan, obtain consent, maintain a treatment register and follow proper procedures for legal representatives."],
    ["RA 11036 — Sec. 21: Suicide prevention","The Act provides for suicide prevention, intervention and response strategies, with attention to youth, and for 24/7 hotlines to be established and strengthened."],
    ["RA 11036 — Sec. 23–25: Education and work","These provisions address mental health in education and workplaces, including curriculum, school programs, mental health professionals and workplace policies."],
    ["RA 11036 — Sec. 27: Barangay health workers","The Act includes training of barangay health workers as part of mental health capacity-building."],
    ["RA 11036 — Sec. 30–38: Agency and local duties","The Act assigns duties across agencies and local government, including social welfare, education, labor, human rights, health and local government bodies."],
    ["RA 11036 — Sec. 38: Geographically isolated areas","People in geographically isolated and disadvantaged areas should have access to mental health services, including through approaches such as home visits or mobile clinics."],
    ["RA 11036 — Sec. 43: Drug dependency","The Act addresses examination of drug dependents for mental health conditions."],
    ["RA 11036 — Sec. 44: Penalties","The Act specifies penalties for listed violations, including certain failures to secure consent, breach of confidentiality, discrimination, and inhumane or unscientific treatment."],
    ["RA 11036 — Least restrictive setting","Sec. 14 includes the principle that services should be provided in the least restrictive setting appropriate to the person's needs."],
    ["RA 11036 — What does the Act say about confidentiality?","Confidentiality is a right under Sec. 5(l); disclosure is limited to the exceptions specified by the Act."],
    ["RA 11036 — What does the Act say about consent and restraint?","Sec. 8 requires written informed consent for a treatment plan, including physical or chemical restraint, with Sec. 13 setting out limited exceptions and safeguards."],
    ["RA 11036 — Why document a Sec. 13 intervention?","Sec. 13(d) requires practice under approved facility guidelines and documentation, with independent monitoring, review and audit."],
    ["RA 11036 — Who makes a Sec. 13 order?","The attending mental health professional; the facility IRB must review within 15 days and every 15 days while the order continues."],
    ["RA 11036 — What is the role of supporters under Sec. 11?","Supporters assist a service user to express preferences and participate in decisions, with safeguards against coercion and abuse; they do not simply replace the person's decision."],
    ["RA 11036 — What does Sec. 6 address?","Rights and support for carers, including support and participation in care planning within the Act's provisions."],
    ["RA 11036 — What does Sec. 16 address?","The Act addresses the integration and delivery of mental health services at the primary-care and community level."],
    ["RA 11036 — What does Sec. 24 address?","Mental health programs in educational institutions are addressed in the Act's education provisions."],
    ["RA 11036 — What does Sec. 31 address?","The Act assigns a role to the Commission on Human Rights in mental health rights-related implementation."],
    ["RA 11036 — What does Sec. 36 address?","The Act assigns social welfare-related responsibilities, including support and services relevant to people and families experiencing social need."],
    ["RA 11036 — What does Sec. 37 address?","The Act addresses local government unit duties related to implementing mental health services and support."],
    ["RA 11036 — What is the purpose of the Act's complaints right?","Service users have a right to raise complaints about violations of their rights under the Act."],
    ["RA 11036 — Is refusal of a recommendation itself proof of incapacity?","No. The Act's definition concerns specified abilities to understand and communicate; disagreement alone is not one of those abilities."],
  ],
  sdoh:[
    ["WHO SDoMH — Core definition","Mental health and many common mental disorders are shaped to a great extent by the social, economic and physical environments in which people live."],
    ["WHO SDoMH — What is the social gradient?","Mental health risks and outcomes vary along a social gradient: disadvantage is not only a simple poor-versus-not-poor divide."],
    ["WHO SDoMH — Inequality and risk","The report states that social inequalities are associated with increased risk of many common mental disorders; greater inequality is associated with greater inequality in risk."],
    ["WHO SDoMH — Life-course approach","Action on living conditions should begin before birth and continue through early childhood, later childhood and adolescence, family-building and working ages, and older age."],
    ["WHO SDoMH — Why early childhood matters","The report highlights scientific consensus that giving every child the best possible start can generate substantial societal and mental health benefits."],
    ["WHO SDoMH — Universal action","Action to improve mental health should be universal across society, rather than limited only to a narrowly defined high-risk group."],
    ["WHO SDoMH — Proportionate universalism","Universal actions should be delivered at a scale and intensity proportionate to need, to help level the social gradient in health outcomes."],
    ["WHO SDoMH — Why not target only the most disadvantaged?","The report notes that targeting only the most disadvantaged will not flatten the social gradient, and targeted services may decay over time."],
    ["WHO SDoMH — Multilevel action","The report discusses action at structural/country, community and local levels, and across the life course and family/household settings."],
    ["WHO SDoMH — What are structural interventions?","Interventions that address broader social, economic or environmental conditions that shape exposure to risks and access to resources."],
    ["WHO SDoMH — What are local interventions?","Actions in everyday settings and services that can reduce exposure to risk or strengthen support and protective resources."],
    ["WHO SDoMH — Poverty and common mental disorders","The report reviews evidence associating poverty with common mental disorders, including studies from low- and middle-income countries."],
    ["WHO SDoMH — Poverty measures","Poverty is not a single measure: studies use indicators such as low income, debt, financial strain, education and employment conditions."],
    ["WHO SDoMH — Debt","The report reviews evidence linking debt and financial strain with mental disorder; asking about debt may reveal risks not captured by income alone."],
    ["WHO SDoMH — Unemployment","Unemployment is discussed as a social and economic condition associated with mental health risks; mental disorder can also affect employment and income."],
    ["WHO SDoMH — Two-way poverty cycle","Poverty can increase mental health risks, while mental disorder can reduce income and employment, further worsening poverty."],
    ["WHO SDoMH — Perinatal mental health","The report describes common perinatal mental disorders and discusses risk factors including intimate partner violence, lack of partner support, unintended pregnancy and socioeconomic disadvantage."],
    ["WHO SDoMH — Family and parenting","Family relationships, parenting and support in early life are among the settings and processes considered in the report's life-course approach."],
    ["WHO SDoMH — School-age children and adolescents","The report calls for action across childhood and adolescence, including attention to school and community settings."],
    ["WHO SDoMH — Older age","The report addresses mental health in older age and discusses social isolation and the importance of social relationships and supportive community approaches."],
    ["WHO SDoMH — Social isolation","Social isolation and limited social relationships are discussed as risks relevant to mental health, including in older age."],
    ["WHO SDoMH — Community-level action","Community programs can support social connection, participation and access to resources, complementing action at other levels."],
    ["WHO SDoMH — Intersectoral action","Because determinants arise outside health services, action may require coordination across sectors and settings, not only clinical care."],
    ["WHO SDoMH — Health services alone?","Clinical services matter, but the report emphasizes that mental health is also shaped by conditions in social, economic and physical environments."],
    ["WHO SDoMH — Risk exposure and buffers","The report describes approaches that reduce exposure to harmful conditions and strengthen protective resources and support across life stages."],
    ["WHO SDoMH — Evidence and context","The report reviews evidence across countries and settings; the strength and availability of evidence can vary by determinant, population and context."],
    ["WHO SDoMH — LMIC evidence gaps","The report notes a significant gap in research and strategies to prevent mental disorders through social determinants in low- and middle-income countries."],
    ["WHO SDoMH — Action before birth","The life-course approach starts before birth because early conditions can shape later development and mental health."],
    ["WHO SDoMH — Work and working ages","Working-age conditions form part of the life course; economic security and employment conditions are relevant to mental health."],
    ["WHO SDoMH — What should an assessment ask beyond symptoms?","In keeping with the report's framework, consider the person's social, economic and physical environments and how these change across the life course."],
    ["WHO SDoMH — Population-level prevention","Improving everyday living conditions can create opportunities to improve population mental health and reduce risks associated with social inequalities."],
    ["WHO SDoMH — Why use a multilevel framework?","Determinants operate at multiple levels, so action in only one setting may miss influences from households, communities, services and wider social conditions."],
    ["WHO SDoMH — What does proportionate intensity mean in practice?","Maintain universal action while increasing the scale or intensity of support in proportion to levels of disadvantage and need."],
    ["WHO SDoMH — Social determinants are not individual blame","The report locates mental health influences in social, economic and physical environments as well as across the life course, rather than treating outcomes as solely individual choices."],
    ["WHO SDoMH — Main prevention opportunity","Comprehensive action across the life course, including early childhood and the conditions of daily life, offers opportunities to improve mental health and reduce unequal risks."],
  ]
};
