// Case studies summarized from WHO & Calouste Gulbenkian Foundation (2014), Social determinants of mental health (pp. 20-38). Reference numbers are the paper's.
// Format: [name, where, stage, level, what, reported results, source, RA 11036 link]
window.INTV=[
["Home visits for early stimulation","Jamaica","Perinatal and early years","Local services","Community health workers from government health centres visited homes weekly for half an hour to demonstrate play activities with child, mother and caregivers, and to discuss parenting, nutrition and learning environments.","Analysis suggests the visits significantly reduced maternal depression.","p.20-21 (ref 42)","Secs. 15, 27"],
["Mother-infant relationship intervention","South Africa","Perinatal and early years","Local services","Randomized trial of an intervention to improve the mother-infant relationship in a socioeconomically deprived community.","Reduced depression in mothers and improved child attachment and interaction over certain time periods.","p.20 (ref 44)","Secs. 15, 16"],
["Triple P-Positive Parenting Programme","Australia; replicated in Hong Kong, Iran, Japan, Switzerland","Perinatal and early years","Family and household","Behavioural family intervention that changes the family environment so the child can realize their potential, delivered with a population approach.","Reported as successfully replicated in several countries; aims to raise life chances and reduce mental health risks.","p.21 (refs 45-49)","Secs. 6, 14"],
["High/Scope Perry, Nurse-Family Partnership, Incredible Years","USA (Incredible Years in 20 countries and territories)","Perinatal and early years","Family and household","Long-studied preschool and home-visiting programs for young children in low-income, poverty-stricken settings.","Improve pregnancy outcomes, school readiness, educational achievement, economic success, and mental and physical health.","p.21 (refs 50-53)","Secs. 6, 15"],
["Mother2Mothers","South Africa (KwaZulu-Natal)","Perinatal and early years","Community","Communities develop peer support groups giving education and psychosocial support to pregnant women and new mothers with HIV/AIDS, including help accessing health services.","Participants had greater psychosocial well-being and made more use of services than non-participants; new mothers gained more, with more contact time.","p.21 (ref 54)","Secs. 16, 37(h)"],
["Sure Start","England","Perinatal and early years","Local services","Government scaled-up early-years initiative engaging parents, pregnant mothers, infants and pre-school children to reduce low birth weight and cognitive delay, improve relationships and attachment, and reduce disadvantage, with services accessible to the most deprived.","Presented as a good example of scaling up early-years intervention.","p.27 (refs 96-97)","Secs. 15, 37(b)"],
["Social and Emotional Learning programme","USA (several States)","Children and adolescents","Local services","School-based program that promotes supportive relationships that make learning engaging and builds social and emotional skills to reduce risky behaviours.","Three large reviews (317 studies, 324,303 children) found benefits in social-emotional skills, attitudes, school engagement, positive behaviour, attainment, conduct and emotional distress.","pp.22-23 (refs 65-66)","Secs. 23, 24, 34"],
["School-based program after civil war","Sri Lanka","Children and adolescents","Local services","15 sessions over 5 weeks delivered by trained non-specialized personnel in randomly selected schools: safety, stabilisation, self-esteem, trauma, coping skills, reconnecting socially and planning ahead. Modelled on an Indonesian program.","Improvements in some participants' mental health and conduct, including settling disputes non-violently.","p.23 (refs 67-68)","Secs. 24, 36(c)"],
["Minimum alcohol pricing","British Columbia, Canada","Working age","Country","Minimum alcohol price adjusted incrementally over about 20 years.","A 1989-2010 study estimates a 10% rise in the minimum price cut consumption of that drink relative to others by 16.1%, and total alcohol consumption by 3.4%.","p.24 (ref 78)","Secs. 22, 30(a)"],
["IMAGE (Intervention with Microfinance for AIDS and Gender Equity)","South Africa","Working age","Community","Group-based microfinance combined with a gender and HIV/AIDS training programme.","Evaluation suggested interpersonal violence fell significantly in participating villages, likely reducing downstream anxiety and depression.","p.25 (ref 87)","Secs. 36(b), 37(f)"],
["Small individual loans","South Africa","Working age","Family and household","Randomized trial of small individual loans as a poverty-alleviation tool.","Depressive symptoms fell among men but not women; the report notes other studies suggest benefits for women.","p.25 (ref 86)","Secs. 36(b), 37(f)"],
["Flexible loan repayment","India (Kolkata)","Working age","Family and household","Randomized trial of monthly versus weekly microfinance repayment.","Monthly-repayment clients were 51% less likely to feel anxious about repayment and reported better income and business investment.","p.25 (ref 88)","Secs. 36(b), 37(f)"],
["Health Promotion Enterprise programme","China (Credibility Retail Enterprise)","Working age","Workplace","Peking University researchers worked with nine firms (300 employees each) over three years: manager training in communication, stress management, problem solving and conflict management, plus employee discussion sessions to improve the work environment.","Pre- and post-surveys showed reduced depression and anxiety, better work performance and less absenteeism.","p.26 (refs 93-94)","Secs. 25, 35"],
["Tyohon Job Search Programme","Finland","Working age","Country","Active labour market program: specialized trainers help with job searching and labour market guidance, with financial support and vocational training. Based on a Michigan program.","At two-year follow-up 70.4% were reemployed, in a subsidized job or in training; participants reported fewer depressive symptoms and higher self-esteem.","p.36 (refs 159-160)","Secs. 35, 36(b)"],
["Meeting of the Minds","Auckland, New Zealand","Older people","Community","Monthly hour-long sessions in 12 community libraries, run with the city council, Age Concern and the Mental Health Foundation: shared histories, lifelong learning, book clubs and talks.","1,085 people attended in the first six months; 38% lived alone and used it to meet new people.","p.29 (ref 109)","Secs. 5(i), 37(h)"],
["Upstream Healthy Living Centre","England","Older people","Community","Mentors deliver tailored activities and support to isolated older people in rural areas to build social networks and creative activity.","Evaluation: improved psychological well-being and reduced depression.","p.29 (ref 110)","Secs. 5(i), 37(h)"],
["BasicNeeds self-help groups","Ghana (also rural Kenya)","All ages","Community","Monthly self-help groups where no psychiatric facilities exist: help with care tasks, collecting wood and water, cooking visits, access to credit, and access to health services.","Groups gave social and financial support; members used services better and completed treatment more often with better outcomes. The Kenya evaluation supported feasibility and improvements in mental health, quality of life, social relations and economic functioning.","pp.30-31 (refs 113-114)","Secs. 16, 37(h)"],
["Comprehensive Rural Health Project","India (Maharashtra)","Working age","Community","Community-based project integrating mental health into primary care with a focus on women: trained volunteers build competence and self-esteem; income generation, agriculture, education and referral.","Women reported benefits of independent labour-market work, more decision-making and freedom of movement, better domestic relationships and better mental health.","p.31 (refs 115-116)","Secs. 15, 27, 36(b)"],
["Integrating mental health into primary care","Uganda (with South Africa in the Mental Health and Poverty Project, 2008-09)","All ages","Local services","1999 reforms put mental health in the Uganda Minimum Health Care Package and decentralized services, supported by referral systems. General health workers, some without formal qualifications, deliver care.","The project helped generate political will; multisectoral collaboration, task shifting and self-help groups were especially promising for the treatment gap.","p.32 (refs 122-124)","Secs. 15, 16, 27"],
["Community sociotherapy for genocide survivors","Rwanda (Byumba district)","All ages","Community","From 2006, with local organizations: re-establishing values, norms and relationships, psychoeducation, shared coping, and practical support among participants.","Reached over 7,000 people; evaluations indicate improved mental health.","p.33 (refs 127-128)","Secs. 36(c), 37(h)"],
["Counselling integrated into primary care","Iraq (MSF with Ministry of Health)","All ages","Local services","Training new and existing counsellors and building services into primary care.","2012 data: 97% of those counselled had mental health issues at admission vs 29% at last visit.","p.33 (ref 129)","Secs. 15, 36(c)"],
["Replacing dirt floors with cement","Mexico","All ages","Family and household","Large-scale housing program.","Better child health and cognitive development; adults reported better well-being with less depression and stress.","p.34 (ref 133)","Secs. 36(b), 37(f)"],
["Warm Front Scheme","England (UK)","All ages","Family and household","Cross-department government grants to improve energy efficiency in low-income households affected by fuel poverty.","Results indicated reduced depression, stress and anxiety.","p.34 (refs 105-106)","Secs. 36(b), 37(f)"],
["National mental health policy with a social-determinants approach","Australia (similar in Scotland and New Zealand)","All ages","Country","Beyond services, the policy considers housing, education, employment, ageing, chronic disease and cultural diversity, with decentralized services, community approaches and cross-sector partnerships.","Presented as an example of building social determinants into national policy.","pp.37-38 (refs 168-171)","Secs. 37(a), 39-41"]
];
