// IRR layer. Source: Department of Health. Implementing Rules and Regulations of Republic Act No. 11036, approved 22 January 2019
// (published in the Philippine Daily Inquirer on 4 February 2019). The text was read on 7 October 2026 from a full-text transcription (Legaldex).
// The official PDF is hosted in the WHO MiNDbank (link below); confirm wording against it before formal use.
// Quoted excerpts below are exact; everything labelled "In practice" is educational interpretation.
window.IRR_SRC = {
  cite: "Department of Health. Implementing Rules and Regulations of Republic Act No. 11036, Otherwise Known as the Mental Health Act. Approved 22 January 2019, Mandaluyong City; published in the Philippine Daily Inquirer, 4 February 2019.",
  primary: "https://extranet.who.int/mindbank/item/6881",
  primaryLabel: "WHO MiNDbank copy (PDF)",
  transcription: "https://legaldex.com/laws/implementing-rules-and-regulations-of-republic-act-no-11036-otherwise",
  read: "7 October 2026"
};

// [act section, IRR section or null, topic]. IRR Sec. 13 (General Guidelines) has no Act counterpart; Act Sec. 46 (the IRR mandate) has no IRR counterpart.
window.IRR_CROSSWALK = [
  ["1", "1", "Short title"], ["2", "2", "Declaration of policy"], ["3", "3", "Objectives"], ["4", "4", "Definitions"],
  ["5", "5", "Rights of service users"], ["6", "6", "Rights of family members, carers and legal representatives"], ["7", "7", "Rights of mental health professionals"],
  ["8", "8", "Informed consent to treatment"], ["9", "10", "Advance directive"], ["10", "11", "Legal representative"], ["11", "12", "Supported decision making"],
  ["12", "14", "Internal Review Board"], ["13", "9", "Exceptions to informed consent"],
  ["14", "15", "Quality of mental health services"], ["15", "16", "Services at the community level"], ["16", "17", "Community-based facilities"], ["17", "18", "Reportorial requirements"],
  ["18", "19", "Services in regional, provincial and tertiary hospitals"], ["19", "20", "Duties of mental health facilities"], ["20", "21", "Drug screening services"],
  ["21", "22", "Suicide prevention"], ["22", "23", "Public awareness"], ["23", "24", "Integration into the educational system"], ["24", "25", "Promotion in educational institutions"],
  ["25", "26", "Promotion and policies in the workplace"], ["26", "27", "Capacity building, reorientation and training"], ["27", "28", "Capacity building of BHWs"],
  ["28", "29", "Research and development"], ["29", "30", "National Center for Mental Health"], ["30", "31", "Duties of the DOH"], ["31", "32", "Duties of the CHR"],
  ["32", "33", "Investigative role of the CHR"], ["33", "34", "Complaint and investigation"], ["34", "35", "DepEd, CHED and TESDA"], ["35", "36", "DOLE and CSC"],
  ["36", "37", "DSWD"], ["37", "38", "Local government units"], ["38", "39", "Upgrading of local hospitals and facilities"], ["39", "40", "Philippine Council for Mental Health: mandate"],
  ["40", "41", "Council: duties and functions"], ["41", "42", "Council: composition"], ["42", "43", "DOH Mental Health Division"], ["43", "44", "Mental health for drug dependents"],
  ["44", "45", "Penalty clause"], ["45", "46", "Appropriations"], ["46", null, "Mandate to issue the IRR"], ["47", "47", "Separability"], ["48", "48", "Repealing clause"], ["49", "49", "Effectivity"],
  [null, "13", "General guidelines (IRR only)"]
];

// Provisions where the IRR adds to or clarifies the Act. kind: adds | clarifies | same.
window.IRR_ADDS = [
  { irr: "8", act: "8", kind: "adds", title: "Documenting informed consent: five minimum principles",
    quote: "The Department of Health (DOH) shall develop guidelines relative to obtaining and documenting informed consent. At a minimum, an informed consent shall respect the following principles: a) Voluntarism ... b) Competency ... c) Disclosure ... d) Understanding ... e) Decision ...",
    summary: "Voluntarism: no threat, coercion, undue influence or manipulation. Competency: the user can understand the information and the consequences, and communicate the decision. Disclosure: benefits, risks, alternatives, and the benefits and risks of not accepting. Understanding: capacity to understand and appreciate foreseeable consequences. Decision: the user authorizes the plan, consistent with authentic preferences or advance directives.",
    practice: "Clinical reasoning: the five headings make a sound structure for a consent note. Confirm whether your institution has adopted the DOH consent guidelines." },
  { irr: "9", act: "13", kind: "same", title: "Exceptions to informed consent (Act Sec. 13)",
    quote: "During psychiatric or neurologic emergencies, or when there is impairment or temporary loss of decision-making capacity on the part of a service user, treatment, restraint or confinement, whether physical or chemical, may be administered or implemented pursuant to the following safeguards and conditions ...",
    summary: "The four safeguards (a) to (d) are worded as in the Act: advance directive followed unless immediate risk of serious harm; only as necessary and only while the emergency or impairment lasts; attending mental health professional's order with IRB review within 15 days then every 15 days; approved guidelines with clear criteria, full documentation and IRB audit.",
    practice: "Cite as 'Act Sec. 13 / IRR Sec. 9'. The numbers differ, and the penalty clause (IRR Sec. 45) still refers to 'Sec. 13 of this Act'." },
  { irr: "13", act: null, kind: "adds", title: "General guidelines: 90 days to operationalize consent rules",
    quote: "Within ninety (90) days from the effectivity of the IRR, DOH in coordination with the CHR and other relevant stakeholders shall develop guidelines to fully operationalize the provisions regarding Informed Consent to Treatment, Exceptions to Informed Consent, Advance Directive, Legal Representative and Supported Decision Making.",
    summary: "A section that exists only in the IRR. It directs DOH and CHR to issue operating guidelines for five consent-related topics.",
    practice: "In practice: ask your medical director or IRB which DOH guideline your facility follows for each topic, and record it in the guideline tracker below." },
  { irr: "14", act: "12", kind: "clarifies", title: "Internal Review Board: scope, guidelines and membership",
    quote: "Health facilities shall refer to the mental health facilities as defined in this IRR. ... The DOH, in coordination with appropriate agencies and guidance from the PCMH, shall issue guidelines and rules of practice relating to the operationalization of the IRB in mental health facilities within six (6) months after the effectivity of the IRR. ... 4) Other members deemed necessary, to be invited by the IRB as ad hoc resource persons when a subject matter expertise is needed.",
    summary: "The Act left item (4) of the IRB's composition to the IRR. The IRR makes the extra members ad hoc resource persons invited when expertise is needed. The three core members remain a DOH representative, a CHR representative and a nominee of an accredited service-user and family organization. Powers and functions are as in the Act.",
    practice: "In practice: the IRB's core membership is three; additional specialists join case by case." },
  { irr: "15", act: "14", kind: "adds", title: "Quality of services: four qualities and periodic review",
    quote: "Further, mental health services shall be accessible, available, affordable, and acceptable; delivered by an adequate number of competent health workers who have been trained to provide mental health care according to their level and setting; provide reasonable accommodation to persons with disabilities; and guided by high professional and ethical standards.",
    summary: "The IRR adds this accessibility standard and says the Council reviews service quality periodically using the reports required by IRR Sec. 18.",
    practice: "Useful as a checklist when auditing a facility or writing a local proposal." },
  { irr: "16", act: "15", kind: "adds", title: "Community services: linkages and a two-year guidance deadline",
    quote: "These services must also actively link peer supports, education, livelihood and employment, social services, and other community support services.",
    summary: "Community mental health services cover wellness promotion, prevention, treatment and rehabilitation, and must be inclusive of vulnerable populations. DOH is to give further guidance and technical assistance on program design, implementation and evaluation within two years after the IRR took effect.",
    practice: "Connects directly to the social determinants approach: services are expected to link to income, education and social support." },
  { irr: "17", act: "16", kind: "adds", title: "What counts as a community-based mental health care facility",
    quote: "For the purpose of this IRR, a community-based mental health care facility refers to a mental health facility outside of a mental hospital.",
    summary: "Examples include community mental health centers, outpatient care centers, halfway houses, crisis centers and drop-in centers. Each has adequate space, mental health professionals, allied professionals, support staff, trained barangay health workers, volunteer family members, basic equipment and supplies, and medicines appropriate to its level.",
    practice: "The WHO assessment counts 1,362 community-based facilities (see Philippine data); this IRR definition explains what is being counted." },
  { irr: "18", act: "17", kind: "adds", title: "LGU quarterly report: mode of confinement and the Data Privacy Act",
    quote: "Subject to the Data Privacy Act, the report shall include, among others, the following data ... Information on the mode of confinement, whether voluntary or involuntary, shall be reported.",
    summary: "Compared with the Act, the IRR adds the Data Privacy Act qualification and requires reporting of voluntary versus involuntary confinement, without disclosing identities.",
    practice: "These reports are the main routine source of local data; compare the Philippine data tab on why national counts are incomplete." },
  { irr: "20", act: "19", kind: "adds", title: "Facilities: document and report unavoidable seclusion or restraint; treatment register",
    quote: "Circumstances surrounding any instance of unavoidable seclusion or restraint shall be properly documented and reported.",
    summary: "Under facility duty (a) the IRR adds this documentation and reporting duty. Under (e) the register must cover pharmacologic and non-pharmacologic interventions (including supplements, herbal or alternative preparations, experimental drugs, psychotherapies and neurostimulation) and adverse reaction reports, under a DOH retention policy and in compliance with the Data Privacy Act. Providers must be trained to give accurate information to users, family members, carers or supporters.",
    practice: "Pair with the Sec. 13 checklist tab: the order, review dates and the circumstances of the restraint all belong in the record." },
  { irr: "21", act: "20", kind: "clarifies", title: "Drug screening may use scales and questionnaires",
    quote: "Drug screening services may include any one or a combination of, but not limited to, laboratory examination, administration of risk assessment scales and screening questionnaires as deemed appropriate.",
    summary: "The Act requires screening capability at each local facility; the IRR clarifies that this need not mean laboratory testing alone.", practice: "" },
  { irr: "22", act: "21", kind: "adds", title: "Suicide prevention: the national strategy and linked hotlines",
    quote: "A national suicide prevention strategy includes, among other components, the following: a) Emergency mental health care for persons in suicide crisis situations; b) Mainstreaming of suicide prevention ...; c) Training of first responders, health professionals and volunteers ...; d) Responsible media reporting and handling of suicide events; and e) Establishing a system for suicide surveillance.",
    summary: "The IRR lists the components, requires 24/7 helplines and crisis hotlines to be coordinated and linked to available services within the territorial jurisdiction of the crisis call, and directs DOH to develop policies on hotlines and strategies.",
    practice: "Check the DOH and NCMH websites for the current hotline numbers before teaching or printing them." },
  { irr: "23", act: "22", kind: "adds", title: "Public awareness includes advocacy for rights",
    quote: "Activities on public awareness shall also include advocacy for respecting, protecting and promoting the rights of persons with psychosocial disabilities and other vulnerable population ...",
    summary: "Coordination includes service user, family and carer groups and the Persons with Disability Affairs Office (PDAO).", practice: "" },
  { irr: "24", act: "23", kind: "adds", title: "Education: two-year content deadline",
    quote: "Within two years after the effectivity of this IRR, age-appropriate content for the promotion of mental health and prevention of mental health conditions shall be made available and accessible to all educational institutions at all levels ...",
    summary: "Materials are developed by DepEd, CHED and TESDA with mental health experts. CHED ensures psychiatry and neurology are required in medical and allied health courses.", practice: "" },
  { irr: "25", act: "24", kind: "same", title: "Educational institutions need mental health professionals",
    quote: "All public and private educational institutions shall be required to have a complement of mental health professionals.",
    summary: "The Act states the same requirement; the IRR adds that DepEd, CHED and TESDA give guidance on promotion, basic support services and linkages.", practice: "" },
  { irr: "28", act: "27", kind: "adds", title: "BHW training and supervision: case finding and referral",
    quote: "The LGUs shall ensure the capacity building and supervision of the BHWs for the promotion of mental health, advocacy for patient's rights, case finding, identification and referral.",
    summary: "Spells out what BHWs are trained and supervised to do.", practice: "Matches the BHW role in the Aling Nena case: identify, support and refer, under supervision." },
  { irr: "29", act: "28", kind: "adds", title: "Regular national epidemiologic study",
    quote: "A national epidemiologic study on mental health shall be undertaken at regular intervals to be determined by the Philippine Council for Mental Health.",
    summary: "The Act does not mention this study. It explains why national prevalence figures often rest on modelled estimates.", practice: "" },
  { irr: "31", act: "30", kind: "adds", title: "DOH: PhilHealth packages and the medicines supply chain",
    quote: "Outpatient and inpatient benefit packages for priority mental health conditions shall be available within two years after the effectivity of this IRR, as determined in the National Mental Health Program; ... Formulate, develop and implement an efficient, effective, and sustainable supply chain of quality medicines for mental health conditions within the context of the community including prepositioning of drugs during disasters;",
    summary: "The IRR sets a two-year target for outpatient and inpatient packages for priority conditions and adds a medicines supply chain duty, including prepositioning during disasters.", practice: "Check current PhilHealth issuances; this app does not verify what is covered today." },
  { irr: "32", act: "31", kind: "adds", title: "CHR: what 'impropriety' means and the right to visit",
    quote: "impropriety shall be defined as the administering of treatment and care without consent; failure to comply with recognized standards on treatment and care; and abuse and exploitation of consent given by the service user. Consent gained by the use of force or coercion shall also be considered as an act of impropriety.",
    summary: "The IRR also gives the CHR an unimpeded right to monitor and visit mental health facilities, defines cruel, inhuman and degrading treatment, creates the Focal Commissioner role, and says the decision of the Commission en banc prevails over the Focal Commissioner's.",
    practice: "Useful when deciding whether a practice could be a rights complaint." },
  { irr: "33", act: "32", kind: "clarifies", title: "CHR investigative role: two statements to read together",
    quote: "The investigative role of the CHR as provided in the pertinent provisions of this Act shall be limited to all violations of human rights involving civil and political rights consistent with the powers and functions of the CHR under Section 18 of Article XIII of the Constitution.",
    summary: "The IRR adds a second paragraph saying the CHR shall investigate, on its own or on complaint, all forms of civil, political, economic, social and cultural human rights violations recognized under international human rights law.",
    practice: "The scope can look inconsistent between the two paragraphs. For a real complaint, ask the CHR rather than relying on either sentence alone." },
  { irr: "34", act: "33", kind: "adds", title: "Complaints: DOH, CHR and DOJ with joint guidelines",
    quote: "The DOH, CHR and Department of Justice (DOJ) shall receive all complaints of improprieties and abuses in mental health care and shall initiate appropriate investigation and action.",
    summary: "The IRR adds a six-month deadline for the three agencies to issue joint implementation guidelines, and lets the CHR file a complaint on its own initiative against institutions it finds noncompliant.", practice: "" },
  { irr: "36", act: "35", kind: "adds", title: "DOLE programs for overseas Filipino workers",
    quote: "DOLE shall also develop mental health programs for Overseas Filipino Workers.",
    summary: "The CSC is to issue policies for national agencies, LGUs, state universities and colleges and government corporations; DOLE guidelines are due within six months.", practice: "Relevant to the OFW family-separation case in the SDoMH library." },
  { irr: "38", act: "37", kind: "adds", title: "LGUs: services for vagrants with mental health problems; one-year guidelines",
    quote: "k) In coordination with appropriate local agencies, ensure mental health and other services are provided to vagrants with mental health problems who are in their respective territorial jurisdiction.",
    summary: "LGU duties also include a local ordinance, a multi-sectoral stakeholder network, drug screening, and appropriations. Guidelines are due within one year.", practice: "" },
  { irr: "40", act: "39", kind: "adds", title: "Council: strategic plan with a balanced scorecard",
    quote: "Within six (6) months after the effectivity of this IRR, the Council shall develop a strategic plan for implementation, including a balanced scorecard with indicators.",
    summary: "It shall include a multi-agency coordinating mechanism with regional and local mental health councils or other appropriate bodies.", practice: "" },
  { irr: "45", act: "44", kind: "clarifies", title: "Penalty clause: IRR Sec. 45, with Act cross-references",
    quote: "a) Failure to secure informed consent of the service user, unless it falls under the exceptions provided under Sec. 13 of this Act; b) Violation of the confidentiality of information, as defined under Sec. 4 (c) of this Act; c) Discrimination ... as defined under Sec. 4 (e) of this Act; and d) Administering inhumane, cruel, degrading or harmful treatment not based on medical or scientific evidence as indicated in Sec. 5 (h) of this Act.",
    summary: "Same four offences and penalty as Act Sec. 44 (6 months to 2 years, or P10,000 to P200,000, or both). Note that the cross-references inside IRR Sec. 45 point to Act section numbers, not IRR numbers.",
    practice: "A common source of confusion: 'Sec. 13' inside IRR Sec. 45 means Act Sec. 13, which is IRR Sec. 9." },
  { irr: "49", act: "49", kind: "adds", title: "Effectivity",
    quote: "These Rules shall take effect fifteen (15) days after publication in the Official Gazette or in at least two (2) newspapers of general circulation.",
    summary: "The IRR was published in the Philippine Daily Inquirer on 4 February 2019, so the fifteen days ran from then. Deadlines in the IRR ('within six months', 'within two years') run from that effectivity.", practice: "" }
];

// Guidelines the IRR directed others to issue. The tracker lets a user note the current issuance; status is NOT verified by this app.
window.IRR_DIRECTIVES = [
  { id: "d8", irr: "8", what: "DOH guidelines on obtaining and documenting informed consent", who: "DOH", when: "No deadline stated" },
  { id: "d13", irr: "13", what: "Guidelines operationalizing informed consent, exceptions, advance directive, legal representative and supported decision making", who: "DOH with CHR and stakeholders", when: "Within 90 days of effectivity" },
  { id: "d14", irr: "14", what: "Guidelines and rules of practice for Internal Review Boards", who: "DOH with agencies, guided by the PCMH", when: "Within 6 months" },
  { id: "d16", irr: "16", what: "Guidance and technical assistance on community, LGU, academic and workplace mental health programs", who: "DOH", when: "Within 2 years" },
  { id: "d17", irr: "17", what: "Guidelines on establishing community-based mental health care facilities", who: "DOH", when: "No deadline stated" },
  { id: "d22", irr: "22", what: "National suicide prevention strategy; policies and guidelines on hotlines and linking to emergency services", who: "DOH with agencies and stakeholders", when: "No deadline stated" },
  { id: "d24", irr: "24", what: "Age-appropriate mental health content for all educational levels", who: "DepEd, CHED, TESDA", when: "Within 2 years" },
  { id: "d30", irr: "30", what: "NCMH evaluation and strategic plan", who: "NCMH", when: "Within 2 years" },
  { id: "d31", irr: "31(f)", what: "PhilHealth outpatient and inpatient benefit packages for priority mental health conditions", who: "DOH with PhilHealth", when: "Within 2 years" },
  { id: "d34", irr: "34", what: "Joint guidelines for receiving and acting on complaints", who: "DOH, CHR, DOJ", when: "Within 6 months" },
  { id: "d36", irr: "36", what: "Workplace mental health guidelines (DOLE) and policies for government workplaces (CSC)", who: "DOLE, CSC", when: "Within 6 months" },
  { id: "d37", irr: "37", what: "DSWD guidelines on referral, housing, livelihood and psychosocial support", who: "DSWD", when: "Within 6 months" },
  { id: "d38", irr: "38", what: "LGU guidelines, including the local mental health ordinance", who: "LGUs", when: "Within 1 year" },
  { id: "d40", irr: "40", what: "Council strategic plan with a balanced scorecard", who: "Philippine Council for Mental Health", when: "Within 6 months" }
];

window.DATA.quiz.push(
  { t: "IRR", q: "Which IRR section contains the exceptions to informed consent that appear in Sec. 13 of the Act?",
    o: ["IRR Sec. 9", "IRR Sec. 13", "IRR Sec. 8", "IRR Sec. 14", "IRR Sec. 12"], a: 0,
    e: "The IRR reorders the Act: exceptions to informed consent are IRR Sec. 9 (Act Sec. 13). IRR Sec. 13 is a different provision: general guidelines, which exists only in the IRR." },
  { t: "IRR", q: "The Internal Review Board is Sec. 12 of the Act. What is its section number in the IRR?",
    o: ["IRR Sec. 14", "IRR Sec. 12", "IRR Sec. 9", "IRR Sec. 20"], a: 0,
    e: "IRR Sec. 14. IRR Secs. 10, 11 and 12 cover the advance directive, legal representative and supported decision making (Act Secs. 9, 10, 11)." },
  { t: "IRR", q: "Which statement matches what IRR Sec. 20 adds about restraint and seclusion?",
    o: ["Circumstances surrounding any instance of unavoidable seclusion or restraint shall be properly documented and reported", "Seclusion is permitted for up to 24 hours without review", "Restraint reports are only needed for chemical restraint", "Documentation is optional if the IRB reviews the order"], a: 0,
    e: "IRR Sec. 20(a) (Act Sec. 19). It adds a documentation and reporting duty to the Act's duty to minimize restrictive care." },
  { t: "IRR", type: "multi", q: "Which of these are listed as minimum principles of informed consent in IRR Sec. 8? Select all that apply.",
    o: ["Voluntarism", "Competency", "Disclosure", "Understanding", "Decision", "Witnessing by a relative", "Payment of a consultation fee", "Notarization"], a: [0, 1, 2, 3, 4],
    e: "IRR Sec. 8 lists voluntarism, competency, disclosure, understanding and decision. Written consent is required by the Act (Sec. 8); notarization applies to advance directives and legal representative designations, not to every consent." },
  { t: "IRR", q: "What data item does IRR Sec. 18 add to the LGU quarterly report, compared with Act Sec. 17?",
    o: ["The mode of confinement, whether voluntary or involuntary", "The patient's name and address", "Household income of each patient", "The treating doctor's license number"], a: 0,
    e: "IRR Sec. 18: subject to the Data Privacy Act, and without disclosing identities, the report also covers voluntary versus involuntary confinement." },
  { t: "IRR", q: "How does IRR Sec. 14 describe the 'other members' of the Internal Review Board?",
    o: ["Ad hoc resource persons invited when subject-matter expertise is needed", "Permanent members appointed by the Secretary of Health", "Elected representatives of the facility's staff", "Court-appointed observers"], a: 0,
    e: "The Act left this item to the IRR (Act Sec. 12(a)(4)). The core members are a DOH representative, a CHR representative and a nominee of an accredited service-user and family organization." },
  { t: "IRR", q: "Within how long after the IRR took effect were DOH and CHR to develop guidelines operationalizing consent, exceptions, advance directives, legal representatives and supported decision making (IRR Sec. 13)?",
    o: ["Ninety days", "Thirty days", "Six months", "Two years"], a: 0,
    e: "IRR Sec. 13: within ninety (90) days. Check which DOH guidelines your facility uses; this app does not verify their current status." },
  { t: "IRR", q: "The penalty clause is Sec. 44 of the Act. What is its section number in the IRR, and what do the section references inside it refer to?",
    o: ["IRR Sec. 45; the references point to Act section numbers", "IRR Sec. 44; the references point to IRR section numbers", "IRR Sec. 46; the references point to Act section numbers", "IRR Sec. 45; the references point to IRR section numbers"], a: 0,
    e: "IRR Sec. 45. Its offence (a) refers to 'Sec. 13 of this Act', which is IRR Sec. 9, so cross-references inside the IRR can use Act numbers." },
  { t: "IRR", q: "Which citation habit best avoids confusion in a chart note or a handout?",
    o: ["Write 'Act Sec. 13 / IRR Sec. 9' and name the document each time", "Write 'Sec. 13' because the Act and IRR use the same numbers", "Cite only the IRR because it is newer", "Cite only the section number without the document"], a: 0,
    e: "The numbering differs for many provisions (for example Act Secs. 9-13 and 44). Name the document, and cite both when it matters." },
  { t: "IRR", type: "multi", q: "Which agencies receive complaints of improprieties and abuses in mental health care under IRR Sec. 34? Select all that apply.",
    o: ["Department of Health", "Commission on Human Rights", "Department of Justice", "Department of Education", "Philippine Health Insurance Corporation", "Department of Labor and Employment"], a: [0, 1, 2],
    e: "IRR Sec. 34 (Act Sec. 33): the DOH, CHR and DOJ receive complaints and initiate investigation and action, with joint guidelines due within six months." }
);
