// Scenarios and audit items are original teaching material written against the text of RA 11036.
window.VIOL=[
["A ward nurse gives an IM sedative to a calm patient who has capacity and refuses medication, because the ward is busy. No emergency exists.",0,"Treatment without consent outside the Sec. 13 exceptions (Sec. 44a). If done by a facility, the penalty reaches the directors, officers or employees responsible."],
["During violent agitation the attending psychiatrist orders chemical restraint per hospital guideline, limited to the emergency, documented, with IRB review scheduled within 15 days.",5,"No violation: all four Sec. 13 safeguards are met."],
["A receptionist tells a caller the diagnosis of a patient admitted last week.",1,"Breach of confidentiality (Sec. 44b); no Sec. 5(l) exception applies."],
["A company declines to hire a qualified applicant solely because she once had treatment for depression, and does not consider reasonable accommodation.",2,"Discrimination (Sec. 44c; Sec. 4e includes denial of reasonable accommodation)."],
["A hospital locks a patient in a bare room for days with no clinical order, no review and no record.",3,"Inhumane, degrading treatment not based on evidence (Sec. 44d); also contrary to Sec. 5(h) (no solitary confinement) and Sec. 19(e)."],
["Three days after admission, a patient says no one has told him his rights.",4,"Rights breach (Secs. 5s and 19b require information within 24 hours), but not one of the four Sec. 44 offences. Address through the IRB, CHR or administrative routes."],
["A psychiatrist facing a negligence complaint gives the chart to the hearing body, limited to what is needed to resolve the case.",5,"No violation: Sec. 5(l)(5) permits disclosure to the extent necessary."],
["A restraint order is renewed weekly for six weeks. The IRB never reviews it.",0,"Sec. 13 requires IRB review within 15 days and every 15 days. Without the safeguards the exception fails, so this is treatment without consent (Sec. 44a)."],
["A patient's request to see her chart is refused because she 'would not understand it'. The attending professional has no concern about harm.",4,"Records may be withheld only if disclosure would harm the user or endanger others (Sec. 5r); she may contest it before the IRB or CHR. Not a Sec. 44 offence."]
];
window.AUDIT=[
{g:"Governance and the IRB",i:[["Internal review board exists with DOH rep, CHR rep and an accredited service-user/family organization nominee","Sec. 12a"],["IRB reviews, monitors and audits treatment, confinement and restraint cases","Sec. 12b"],["IRB reviews each restraint or involuntary treatment order within 15 days, then every 15 days","Sec. 13c"],["Written policies to minimize restrictive care and involuntary treatment","Sec. 19a"],["Approved guideline with clear start and stop criteria for restraint","Sec. 13d"]]},
{g:"Rights and consent",i:[["Rights explained within 24 hours of admission, in a language the patient understands","Secs. 5s, 19b"],["Written informed consent recorded before treatment","Secs. 8, 5m"],["Full treatment plan information given to every user","Sec. 19c"],["Advance directives checked and followed","Secs. 9, 13a"],["Legal representatives designated only through the proper procedure","Secs. 10, 19f"],["Pathway for patients to see records and contest withholding","Sec. 5r"],["Private communication and visitors allowed, including lawyer and CHR","Sec. 5p"],["Complaint route known to patients and families","Secs. 5t, 12b, 33"]]},
{g:"Records and reporting",i:[["Register of all treatments and procedures given","Sec. 19e"],["Quarterly de-identified report to the LGU/DOH (numbers, conditions, age, gender, education, employment)","Sec. 17"],["Chart access limited to authorized staff","Secs. 4c, 5l"]]},
{g:"Services (tertiary, provincial and regional hospitals)",i:[["Short-stay psychiatric or neurologic inpatient ward","Sec. 18a"],["Partial hospital care","Sec. 18b"],["Outpatient service linked to primary care programs","Sec. 18c"],["Home care for patients with special needs","Sec. 18d"],["Coordination with drug rehabilitation centers","Sec. 18e"],["Referral system with public and private providers","Sec. 18f"],["Drug screening capability","Sec. 20"],["Suicide intervention and hotline information","Sec. 21"]]},
{g:"Environment and staff",i:[["Safe, therapeutic, hygienic setting with sufficient privacy","Sec. 30b"],["No solitary confinement or degrading conditions","Sec. 5h"],["No forced or inadequately paid patient labor unless part of accepted therapy","Sec. 30g"],["Staff trained in human rights","Sec. 30l"],["Mental health professionals and workers trained for evidence-based, gender-sensitive care","Sec. 26"]]}
];
window.DATA.cases.push({title:"Rico, 24: drug case and low mood",intro:"Rico, 24, has availed of voluntary submission under RA 9165 after two years of methamphetamine use. At intake he is tearful, sleeps poorly and says it would be easier if he were not around. His mother wants him admitted. Later, a lawyer asks for his chart.",steps:[
{q:"What does Sec. 43 require?",o:[["Treat only the substance dependency",0,"Sec. 4(a) and 4(f) frame addiction as a mental health matter, and Sec. 43 goes further."],["Examine for mental health conditions and, if found, cover him under the Act",1,"Right (Sec. 43). Drug screening capability is expected at local facilities (Sec. 20)."],["Refer him to police for disposition",0,"Nothing in the Act makes the clinician an enforcement agent."]]},
{q:"How do you respond to his passive suicidal thoughts?",o:[["Wait until withdrawal and detox are over",0,"Risk needs assessment now."],["Ask directly, assess plan and means, make a safety plan, involve supports, give hotline details (Sec. 21)",1,"Right. Asking about suicide does not plant the idea."],["Report him to the police",0,"Not an exception to confidentiality (Sec. 5l)."]]},
{q:"His mother wants him admitted. He has capacity and refuses.",o:[["Mother consents as his representative",0,"A default representative acts as substitute only when capacity is assessed as impaired (Sec. 10)."],["Presume capacity (Sec. 8); offer voluntary options; involuntary care only under the Sec. 13 emergency or impairment safeguards",1,"Right. Document your capacity assessment and what was offered."],["Admit him because he has a drug charge",0,"A charge does not remove consent rights; Sec. 5(c) guarantees the same standard of care."]]},
{q:"The lawyer asks for his chart.",o:[["Send it; lawyers are entitled to charts",0,"Confidentiality is the rule (Sec. 5l)."],["Release only with his consent or a court order, through hospital counsel, and only what is required",1,"Right (Sec. 5l-1, -2). Breach carries a penalty (Sec. 44b)."],["Refuse all requests permanently",0,"Consent and court orders are valid routes."]]}]});
